### ISSUE TITLE
Slash in build name

### ISSUE THREAD

**Issue by Lurius** [cmmcleod/coriolis#105]
I saved my build as Current/Trade and now, when selected, I can't delete it (button inactive) and even if no changes are made, Save-button will stay active. Name is displayed as Current%2FTrade.
![coriolis bug](https://cloud.githubusercontent.com/assets/15050339/10394625/13022e2a-6ea1-11e5-8d85-549b14f93ec5.jpg)

**Comment by cmmcleod** [comment]
This is caused by bugs in ui-router:

https://github.com/angular-ui/ui-router/issues/1119

Workaround found for now.
