### ISSUE TITLE
Remove the now redundant A-Rated build option D:

### ISSUE THREAD

**Issue by Piehthyte** [cmmcleod/coriolis#106]
I used this option quite a lot when it was on the website, was wondering why it became redundant? Extremely useful and made a build go extremely fast.

**Comment by cmmcleod** [comment]
It was largely redundant since you can now select an A rated common quick-build. It was also confusing to have `A-rated` build option alongside the `A` quick build option.

Granted you have to now select the best shield manually in addition to the above..
