### ISSUE TITLE
Bad french translation

### ISSUE THREAD

**Issue by Bimnomercy** [cmmcleod/coriolis#108]
Both "Prospector Limpet Controller" and "Collector Limpet Controller" are translate "Contrôleur De Prospecteur".

The right translations are :

"Prospector Limpet Controller" -> "Contrôleur De Prospecteur"
"Collector Limpet Controller" -> "Contrôleur De Collecteur"

Thank you.

**Comment by cmmcleod** [comment]
Fixed by #109
