### ISSUE TITLE
ship cannot be viewed or removed

### ISSUE THREAD

**Issue by ericbakker** [cmmcleod/coriolis#110]
Browser:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
Path:
/outfit/cobra_mk_iii/[object Object]
Error:
unknown
Message:
Cannot read property 'pGen' of undefined
Details:
TypeError: Cannot read property 'pGen' of undefined
    at Ship.updatePower (http://cdn.coriolis.io/app.2cbeb0be.js:42:7867)
    at Ship.buildWith (http://cdn.coriolis.io/app.2cbeb0be.js:42:4797)
    at toShip (http://cdn.coriolis.io/app.2cbeb0be.js:12:1750)
    at new <anonymous> (http://cdn.coriolis.io/app.2cbeb0be.js:20:2988)
    at e (http://cdn.coriolis.io/lib.ee2a1d32.js:6:16969)
    at Object.instantiate (http://cdn.coriolis.io/lib.ee2a1d32.js:6:17086)
    at http://cdn.coriolis.io/lib.ee2a1d32.js:7:5946
    at http://cdn.coriolis.io/lib.ee2a1d32.js:12:23333
    at aa (http://cdn.coriolis.io/lib.ee2a1d32.js:7:2180)
    at K (http://cdn.coriolis.io/lib.ee2a1d32.js:6:28558)

**Comment by cmmcleod** [comment]
Can you copy the URL?

**Comment by ericbakker** [comment]
http://coriolis.io/outfit/cobra_mk_iii/%5Bobject%20Object%5D?bn=Cobra%20Mk%20III

 

 

Van: Colin McLeod [mailto:notifications@github.com] 
Verzonden: vrijdag 16 oktober 2015 0:13
Aan: cmmcleod/coriolis <coriolis@noreply.github.com>
CC: ericbakker <eric@epabakker.com>
Onderwerp: Re: [coriolis] ship cannot be viewed or removed (#110)

 

Can you copy the URL?

**Comment by ericbakker** [comment]
Here are my ships:

http://coriolis.io/outfit/asp/05C5D5A4C4C5D5C0s0s2418241800060606054b5802020024.Iw18WQ==.EwBhrSu7iA==?bn=Hermes

 

The Cobra is the problem (the link in the previous email).

 

Thanks for your help.

 



 

 

Van: Eric Bakker [mailto:eric@epabakker.com] 
Verzonden: vrijdag 16 oktober 2015 0:19
Aan: 'cmmcleod/coriolis' <reply@reply.github.com>
Onderwerp: RE: [coriolis] ship cannot be viewed or removed (#110)

 

http://coriolis.io/outfit/cobra_mk_iii/%5Bobject%20Object%5D?bn=Cobra%20Mk%20III

 

 

Van: Colin McLeod [mailto:notifications@github.com] 
Verzonden: vrijdag 16 oktober 2015 0:13
Aan: cmmcleod/coriolis <coriolis@noreply.github.com <mailto:coriolis@noreply.github.com> >
CC: ericbakker <eric@epabakker.com <mailto:eric@epabakker.com> >
Onderwerp: Re: [coriolis] ship cannot be viewed or removed (#110)

 

Can you copy the URL?

**Comment by cmmcleod** [comment]
ok so the problem is the link that is being generated

http://coriolis.io/outfit/cobra_mk_iii/**%5Bobject%20Object%5D**

The text in bold is obviously not valid. Is this link coming from the build menu or a comparison? 

If it is can you please give me your backup data: `Settings (top right) -> Backup` copy and paste it here.

If it is not coming from the build menu, can you please tell me where the link is coming from?

**Comment by cmmcleod** [comment]
There was only one ship listed in your previous email (Asp - Hermes)

**Comment by ericbakker** [comment]
Yes, the problem link is coming from the ‘Builds’ menu. It concerns the “cobra_mk_iii”

 

{

  "builds": {

    "cobra_mk_iii": {

      "Cobra Mk III": {

        "code": "24A4A4A3A3A3A4C0s0s242400014503592p-2h.Iw1-kA==.Aw1-kA==",

        "useName": "Cobra Mk III"

      },

      "Who's laughing now?": "24A4A4A3A3A3A4C0s0s242400010359452p012h.Iw1-kA==.AwiMIypI"

    },

    "vulture": {

      "Tender Touch": "04A5C4A3C5A4A3C0v1f00---4b5d2o0066.Iw19kA==.IwBhrSrViA=="

    },

    "asp": {

      "Hermes": "05C5D5A4C4C5D5C0s0s2418241800060606054b5802020024.Iw18WQ==.EwBhrSu7iA=="

    },

    "diamondback": {

      "Crazy Diamond": "04A4A4A2C3A2A4C0s0s24240005--4059022h.Iw1-kA==.IwBhrSukg==="

    }

  },

  "comparisons": {},

  "insurance": null,

  "discounts": null

}

 

Van: Colin McLeod [mailto:notifications@github.com] 
Verzonden: vrijdag 16 oktober 2015 0:18
Aan: cmmcleod/coriolis <coriolis@noreply.github.com>
CC: ericbakker <eric@epabakker.com>
Onderwerp: Re: [coriolis] ship cannot be viewed or removed (#110)

 

ok so the problem is the link that is being generated

http://coriolis.io/outfit/cobra_mk_iii/**%5Bobject%20Object%5D**

The text in bold is obviously not valid. Is this link coming from the build menu or a comparison? 

If it is can you please give me your backup data: Settings (top right) -> Backup copy and paste it here.

If it is not coming from the build menu, can you please tell me where the link is coming from?

**Comment by ericbakker** [comment]
I  am not sure what to do now.

Maybe I do not understand how Coriolis is supposed to work.

I see four builds in the menu and sent you the backup info.

 

What do you need to help me get rid of the not working Cobra build in the menu?

 

 

Van: Colin McLeod [mailto:notifications@github.com] 
Verzonden: vrijdag 16 oktober 2015 0:23
Aan: cmmcleod/coriolis <coriolis@noreply.github.com>
CC: ericbakker <eric@epabakker.com>
Onderwerp: Re: [coriolis] ship cannot be viewed or removed (#110)

 

There was only one ship listed in your previous email (Asp - Hermes)

**Comment by cmmcleod** [comment]
Ok, So I know what is wrong, but I haven't figured out how it happened yet. The problem is with how your Cobra build got saved.

Notes for myself
```json
{
    "builds": {
        "cobra_mk_iii": {
            "Cobra Mk III": {  // This is invalid: it should be a string not an object
                "code": "24A4A4A3A3A3A4C0s0s242400014503592p-2h.Iw1-kA==.Aw1-kA==",
                "useName": "Cobra Mk III"
            },
            "Who's laughing now?": "24A4A4A3A3A3A4C0s0s242400010359452p012h.Iw1-kA==.AwiMIypI"
        },
        .....
}

```

**How to fix**

Go to `Settings` -> `Delete all` -> `Yes`
Go to `Settings` -> `Import` ->  *Copy and paste the JSON below* -> `Proceed` -> `Import`

```json
{
    "builds": {
        "cobra_mk_iii": {
            "Cobra Mk III": "24A4A4A3A3A3A4C0s0s242400014503592p-2h.Iw1-kA==.Aw1-kA==",
            "Who's laughing now?": "24A4A4A3A3A3A4C0s0s242400010359452p012h.Iw1-kA==.AwiMIypI"
        },
        "vulture": {
            "Tender Touch": "04A5C4A3C5A4A3C0v1f00---4b5d2o0066.Iw19kA==.IwBhrSrViA=="
        },
        "asp": {
            "Hermes": "05C5D5A4C4C5D5C0s0s2418241800060606054b5802020024.Iw18WQ==.EwBhrSu7iA=="
        },
        "diamondback": {
            "Crazy Diamond": "04A4A4A2C3A2A4C0s0s24240005--4059022h.Iw1-kA==.IwBhrSukg==="
        }
    }
}
```

This will fix the issue. Please let me know that it did fix the issue :)

To help me prevent this issue from happening in the future it would be great if you could tell me:
 - Have you used the import feature before?
 - Did you import the Cobra build from somewhere?
 - How did you create the Cobra build in the first place if it wasn't imported?

I will do some investigating to figure this out.

**Comment by ericbakker** [comment]
Hi,

 

Thank you for your help.

I will tell you a bit more how I use Coriolis, and that might be part of the problem.

 

First of all, I use it on two computers: my home PC where Elite is installed, and my laptop.

I notice that changes that I make on the one are not visible on the other. I assume your site somehow saves the data linked to a pc or browser that is used.

 

To overcome this problem, I save the URL of my ships on Coriolis in my bookmarks, and always load a saved ship first. This helps me (I think).

 

Then the problematic Cobra has been somebody else’s ship. It was my first encounter with Coriolis when somebody posted a link to his Cobra outfitting in a forum, and I clicked it, looked at it, and then made my own Cobra outfitting and saved that under a different ships name.

 

My impression is that the original Cobra, apparently from a CMDR Jameson, has been deleted now by him and causing problems to my saved ships records. But this is just my assumption.

As such, no problem for me, but the trouble was that I could not delete this ship from my builds list.

 

One last remark: I work now on my laptop, checked the Builds list, and the problem Cobra is not on it. I think at home it is still there and I need to apply your fix first.

Is there a way to share my Builds between different computers?

 

Kind regards,

Eric Bakker

 

 

Van: Colin McLeod [mailto:notifications@github.com] 
Verzonden: vrijdag 16 oktober 2015 01:00
Aan: cmmcleod/coriolis <coriolis@noreply.github.com>
CC: ericbakker <eric@epabakker.com>
Onderwerp: Re: [coriolis] ship cannot be viewed or removed (#110)

 

Ok, So I know what is wrong, but I haven't figured out how it happened yet. The problem is with how your Cobra build got saved.

Notes for myself

{
    "builds": {
        "cobra_mk_iii": {
            "Cobra Mk III": {  // This is invalid: it should be a string not an object
                "code": "24A4A4A3A3A3A4C0s0s242400014503592p-2h.Iw1-kA==.Aw1-kA==",
                "useName": "Cobra Mk III"
            },
            "Who's laughing now?": "24A4A4A3A3A3A4C0s0s242400010359452p012h.Iw1-kA==.AwiMIypI"
        },
        .....
}

How to fix

Go to Settings -> Delete all -> Yes
Go to Settings -> Import -> Copy and paste the JSON below -> Proceed -> Import

{
    "builds": {
        "cobra_mk_iii": {
            "Cobra Mk III": "24A4A4A3A3A3A4C0s0s242400014503592p-2h.Iw1-kA==.Aw1-kA==",
            "Who's laughing now?": "24A4A4A3A3A3A4C0s0s242400010359452p012h.Iw1-kA==.AwiMIypI"
        },
        "vulture": {
            "Tender Touch": "04A5C4A3C5A4A3C0v1f00---4b5d2o0066.Iw19kA==.IwBhrSrViA=="
        },
        "asp": {
            "Hermes": "05C5D5A4C4C5D5C0s0s2418241800060606054b5802020024.Iw18WQ==.EwBhrSu7iA=="
        },
        "diamondback": {
            "Crazy Diamond": "04A4A4A2C3A2A4C0s0s24240005--4059022h.Iw1-kA==.IwBhrSukg==="
        }
    }
}

This will fix the issue. Please let me know that it did fix the issue :)

To help me prevent this issue from happening in the future it would be great if you could tell me:

*	Have you used the import feature before?
*	Did you import the Cobra build from somewhere?
*	How did you create the Cobra build in the first place if it wasn't imported?

I will do some investigating to figure this out.

**Comment by cmmcleod** [comment]
Builds are saved to your browser, so they won't sync across other computers or other browsers. It doesn't matter if CMDR Jameson or any other user deletes their builds, once you have a link to their build that is all you need to load it (the link contains all the information to create the build).

Right now the only way to sync across browsers/devices/computers is to use `Settings` -> `Backup` and then `Settings` -> Import.

This means you will have to copy the backup JSON and send it to the other computer/device (e.g. email).

The save feature has been requests by issue #12.
