### ISSUE TITLE
Adding an A4 shield cell bank, it becomes disabled in the power section. Trying to enabled it result in the "Jameson we have a problem"

### ISSUE THREAD

**Issue by nemesyssoft** [cmmcleod/coriolis#111]
Not sure what is wrong. As soon as I add an A4 shield cell bank to my Anaconda, and it is the only one, it appears disabled in the power section, which gives false power output. Trying to enable it result in the "Uh, Jameson, we have a problem".

My loadout is here: http://coriolis.io/outfit/anaconda/08C7D6A5D8D8D4C-0v0v0v1c1c22220404------06050505p232f5f46g5d2f.Iw18Z4AzUA==.IzAM7N1EW+a0TAcgQxelQ===?bn=Laurent%20Anaconda

**Comment by nemesyssoft** [comment]
Oh, for some reason, my jump range is wrong. Coriolis reports 18.73 laden and 25.76 unladen but ED reports 18.47 laden and 25.29 unladen.

Also, I did purchase it from Ray Gateway in Daiguandri. I believe the discount is 15%. When I set the ship discount in Coriolis, it reports the price to be 120M but I paid 124M. The components prices are correct when I set also the components discount to 15%.

**Comment by cmmcleod** [comment]
Ok first issue: The URL has invalid data causing the issue.

This link should work for you:
http://coriolis.io/outfit/anaconda/08C7D6A5D8D8D4C-0v0v0v1c1c22220404------06050505p232f5f46g5e2f.Iw18ZlA=.IwBjNc2HK-qJEA==

Did you copy and paste the build from anywhere? or did you create a new anaconda build from scratch?

The more details you can provide the more likely I will be able to fix/prevent this from happening in the future. Thanks!

Second issue:
Can you provide screen shots of your modules screen? (All modules, might need multiple screenshots)

Third Issue:
The 120M is for the hull only. If you look at the stock Anaconda price with 15% off both ship and components the price is 124.9M

**Comment by nemesyssoft** [comment]
Hello Collin.

First issue: the build came from ED Market Connector. I guess I would need to let the guy know. When I brought the JSON into coriolis, several components were missing so I had to complete the loadout manually.

Second issue: here are the screenshots:




I’m going to get in touch with the guy making ED Market Connector.

Third issue: got it. It makes sense, doh!

Thanks!

-Laurent.
-- 
Laurent Daudelin							laurent@nemesys-soft.com <mailto:laurent@nemesys-soft.com>
AIM/iChat/Skype:LaurentDaudelin 				http://www.nemesys-soft.com/ <http://www.nemesys-soft.com/>
Logiciels Nemesys Software

**Comment by cmmcleod** [comment]
Hi Laurent,

That certainly explains the first issue. 

Unfortunately it seems the screenshots did not upload. If you have trouble uploading them here you could always use imgur.

Thanks!

**Comment by nemesyssoft** [comment]
Duh! I think I never tried to upload them. Ticket is closed but here they are anyway

![anaconda hardpoints 1](https://cloud.githubusercontent.com/assets/2309889/10564658/02ab9dd2-758a-11e5-9c4f-2dd27f57df48.jpg)
![anaconda internals 1](https://cloud.githubusercontent.com/assets/2309889/10564659/06556256-758a-11e5-9eeb-0b8637488c72.jpg)
![anaconda internals 2](https://cloud.githubusercontent.com/assets/2309889/10564660/08e5c1b4-758a-11e5-9e03-9c4f1d19fcc2.jpg)

**Comment by cmmcleod** [comment]
Ah I see the issue:

The link I posted used a 4B Shield Cell Bank. This link uses the correct 4A SCB:

http://coriolis.io/outfit/anaconda/08C7D6A5D8D8D5C-0v0v0v1c1c22220404------06050505p232f5f46g5d2f.Iw18ZlA=.IwBjNc2HK-qJEA==

As you can see the Jump ranges match correctly :)
