### ISSUE TITLE
Old front page

### ISSUE THREAD

**Issue by smartroad** [cmmcleod/coriolis#115]
While I may be on my own here, I miss the old ship buttons front page. Now you open up and are presented with this huge list.

Could there be a compromise. The old buttons could have some of the more pertinent information, Ship name, manufacturer, purchase price, jump range (std/max), hard points and maybe max cargo?

The list could a link in the 'Ships' menu. Just a thought :grin:

**Comment by cmmcleod** [comment]
The homepage is going to evolve over time, and in the future will provide a better overview of your builds, etc. So I won't be going back to the sip buttons, but I will try to improve the menus for mobile and tablet devices.
