### ISSUE TITLE
Diamondback Scout - Adding Cannon on Medium Hardpoint

### ISSUE THREAD

**Issue by milaanisty** [cmmcleod/coriolis#117]
Browser:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9
Path:
/outfit/diamondback/14A4A4A2D3A2D4C1k17------4002026b.Iw1-kA==.Aw1-kA==
Error:
unknown
Message:
undefined is not a function (evaluating 'elem.getAttribute("cpid")')
Details:
select@http://cdn.coriolis.io/app.2cbeb0be.js:20:5629
fn
f@http://cdn.coriolis.io/lib.ee2a1d32.js:10:30333
$eval@http://cdn.coriolis.io/lib.ee2a1d32.js:8:772
$apply@http://cdn.coriolis.io/lib.ee2a1d32.js:8:1007
http://cdn.coriolis.io/lib.ee2a1d32.js:10:30390
c@http://cdn.coriolis.io/lib.ee2a1d32.js:6:14982

**Comment by cmmcleod** [comment]
Can you try right-clicking on the desired Hardpoint (that should empty it) and select the Cannon again?

Which cannon were you trying to select?

This error should have been fixed, but clearly something strange is happening.

**Comment by milaanisty** [comment]
i tried to select the Cannon 2D/F
today i couldn't reproduce it anymore..

**Comment by cmmcleod** [comment]
I will make some changes to mitigate this issue further. Closing for now
