### ISSUE TITLE
gimbaled multicannon power draw is incorrect

### ISSUE THREAD

**Issue by YinYin-Falcon** [cmmcleod/coriolis#118]
The class 2 is too high and the class 1 too low.

**Comment by cmmcleod** [comment]
Can you provide more details or references?

Current Power Draw:
2F/G Multicannon - power 0.64 MW
1F/G Multicannon - power 0.37 MW

References (E:D Shipyard, elite-dangerous.wikia.com, https://forums.frontier.co.uk/showthread.php?t=55365)

**Comment by cmmcleod** [comment]
I have confirmed the power draw in-game and it is correct

In-game Power Draw:
2F/G Multicannon - power 0.64 MW
1F/G Multicannon - power 0.37 MW
