### ISSUE TITLE
Ships price wrong on outfitting page

### ISSUE THREAD

**Issue by mooop12** [cmmcleod/coriolis#122]
The price of all ships is wrong when outfitting them, it's lower by a few percent compared to what it should be. Looking at the source there are two prices in there for each ship, a `hullprice` and a `retailprice`. Not sure what the hull price is used for but when buying ships in game the retail price seems to be correct, and that price is the one shown in the table on the main page.

**Comment by cmmcleod** [comment]
The hull price is the cost of the ships hull excluding any default modules/components.

The retails price is the hull price + all of the standard modules that you get when you buy a 'stock' ship.

You'll notice that the total price shown on each ship outfitting page (before making any changes) will equal the retail price (as shown on the home page).
