### ISSUE TITLE
Armor And sheild values on coriolis starport calulator are wrong

### ISSUE THREAD

**Issue by Geeknificent** [cmmcleod/coriolis#124]
On the ship calculator the values for the armor and sheilds on some ships are wrong. I have circled the values in red. the 5D reinforcment package only gives 240 armor points and the 4D package only gives 120 armor points. with the build on the anaconda currently used the total should only be 1683

In the field for the federal corvette I have highlighted the shields and the hull packages as they are using the same shield build and therefore their shield values should be the same

![wrong values](https://cloud.githubusercontent.com/assets/16213170/11665985/bb632dde-9daf-11e5-9247-093c7c64a943.png)

![wrong values 2](https://cloud.githubusercontent.com/assets/16213170/11666097/5aeb1b0a-9db0-11e5-94f9-313bccbc4d30.png)

**Comment by cmmcleod** [comment]
Can you provide links to the builds?

**Comment by Geeknificent** [comment]
http://coriolis.io/outfit/anaconda/18A7D6A5A8A8D5C2g2g0t0t1l1l0q0q040404040404040f4k05055n2df5376l2b0n2f.AwRj4ypUOXRA.IwBj4yulXI==?bn=Balanced%20anaconda

http://coriolis.io/outfit/federal_corvette/18A7D6A5A8A8A5C2g2g0o27270q0q040404040404040e4k06065n112d372b6l2f.Iw18RAM5A===.IwBj4ytKVI==?bn=Balanced%20corvete

**Comment by cmmcleod** [comment]
The base shields and base armour for the Anaconda and Federal Corvette are not the same, and therefore should be different. Did you mean something else?

Also the hull reinforcement values have been buffed/improved in 1.5 Ships / 2.0 Horizons which is what is show in Coriolis at the moment.

**Comment by Geeknificent** [comment]
Okay makes sense, I just thought it was strange that the values were so different from what I was seeing in the actual game.

**Comment by cmmcleod** [comment]
Yeah, there is also a bit of confusion when a Beta is out because users want to see the latest/Beta stats in Coriolis.io even though the aren't in the released game yet.

Thanks for checking / following up thought!
