### ISSUE TITLE
SCB : needs to insert T-Load introduced by version 1.5 & 2.0

### ISSUE THREAD

**Issue by koreldan** [cmmcleod/coriolis#125]
In version 1.5 & 2.0 of Elite Dangerous client the SCB will have an amount of T-Load when they will be used.
A "T-Load" factor should be added to SCB modules when all data about this will be collected

A source about this:
https://forums.frontier.co.uk/showthread.php?t=200585

**Comment by koreldan** [comment]
Some personal test about it.... ship: Python

SCB class 3A:
x1 SCB 3A = 30% -> 72% ( increment 42% )
x2 SCB 3A = 29% -> 139% ( increment 110% )
x3 SCB 3A = 30% -> 213% ( increment 183% )

SCB classe 3B:
x1 SCB 2B = 30% -> 71% ( increment 41% )
x2 SCB 2B = 29% -> 139% ( increment 110% )
x3 SCB 2B = 31% -> 217% ( increment 186% )

SCB classe 2B:
x1 SCB 2B = 30% -> 60% ( increment 30% )
x2 SCB 2B = 30% -> 100% ( increment 70% )
x3 SCB 2B = 30% -> 140% ( increment 110% )

SCB classe 2A:
x1 SCB 2A = 31% -> 58% ( increment 27% )
x2 SCB 2A = 31% -> 96% ( increment 65% )
x3 SCB 2A = 31% -> 147% ( increment 116% )

**Comment by cmmcleod** [comment]
This info is not available and will be in the next release
