### ISSUE TITLE
Charge per SCB use needs to be updated

### ISSUE THREAD

**Issue by AngelAesahaettr** [cmmcleod/coriolis#126]
1.5 made modifications to the shields recharged per use with smaller ones being nerfed and larger ones being buffed significantly. I have not seen any data collected on this or any official numbers yet.

**Comment by AngelAesahaettr** [comment]
https://www.reddit.com/r/EliteDangerous/comments/3vtk7d/14_vs_20_scb_strength_results_chargecell_in_mj/

**Comment by amarshall** [comment]
Submitted pull request: cmmcleod/coriolis-data#12.

**Comment by cmmcleod** [comment]
Fixed by https://github.com/cmmcleod/coriolis-data/commit/df88dd9afb1b577baff231096ffef7430ac2d853
