### ISSUE TITLE
Suggestion: include small bits of documentation/information

### ISSUE THREAD

**Issue by birdspider** [cmmcleod/coriolis#127]
Hi,

fantastic tool you set up here !

Still I have some issues with a little bit of documentation:

* What does 'Optimize' do, specificly why does it reset my bulkhead choice to 'Lightweight Alloys' ?
* There are some weapons which (I think, haven't played since powerplay) are only obtainable via faction rank (distruptor, etc). Maybe somehow mark them as such.
* In general, since this tool is a very nice what-parts-are-in-the-game "overview", I suggest a togglable settings entry i.e. "Tooltip Descriptions" which gives a basic description of the module on hover (or other method since it may be claimed by #13).

I could take a stab to implement it myself, but I'm lacking the module information pre se.

**Comment by cmmcleod** [comment]
Tooltips are coming/ in progress (I've created #128 to track this).

These are all great suggestions and I will incorporate all of them :)

'Optimize' sets the standard modules to the lowest mass / optimal jump range while providing sufficient power, etc for everything else that is installed/mounted. I can definitely be renamed to 'Optimal Jump Range' or something along those lines.
