### ISSUE TITLE
Show Component potential change on hover

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#13]
When a component is hovered in the select menu, show the potential changes to stats (similar to in-game experience)

**Comment by Toxicat** [comment]
Sounds interesting. I can take a look. Did you planned to use a particular lib/plugin to display a tooltip ?

**Comment by cmmcleod** [comment]
Sounds good. Nothing planned, other than using something AngularJS friendly, and ideally avoid other dependencies/frameworks like jQuery, etc.

**Comment by Toxicat** [comment]
I could make a service/factory for that, not difficult. I'll start this evening, after my day of work (fr time).

**Comment by cmmcleod** [comment]
Released - Beta
