### ISSUE TITLE
Imperial Eagle got a second Class 1 internal slot with 1.5/2.0

### ISSUE THREAD

**Issue by ArghArgh200** [cmmcleod/coriolis#130]
Looks like FDEV snuck it in. Screens (taken Dec 17, 2015, 0200 Pacific)
![impeagle internals shot](https://arghlex.net/u/JzxQXGjeY82H.png)

**Comment by Shardinara** [comment]
Its the eagle and the sidewinder both got an extra slot, also the costs for the cobra mk IV are wildly different also power use seems to have changed maybe to offset SRV module power requirements.

**Comment by cmmcleod** [comment]
The Sidewinder, Eagle, and Imperial Eagle have been updated by https://github.com/cmmcleod/coriolis-data/commit/8735594cfc9aa4548cd016e44057009c8e6eca90 and https://github.com/cmmcleod/coriolis-data/commit/1a012b94e9081eb85a70ffdcb04e2786d5700b9b

Costs are definitely off for a couple of things and I'm tracking this separately. 

What power use changes are you referring to @Shardinara?

**Comment by Shardinara** [comment]
Hiya sorry about the vagueness, i reconfigured a cobra Mk-iii in game v1.5/2.0 and did the same layout in Coriolis, then i noticed the total power was different, double checked the layout was identical - jump distance and mass same, but Coriolis had 7.92mw power use, then to my surprise in game the ship only used 7.34mw, i could not find any other reason for the difference.

**Comment by cmmcleod** [comment]
can you provide a link to the coriolis build and screenshots of your cobra from the outting menu?

**Comment by Shardinara** [comment]
I'm trying to work out how to do that now thanks.

**Comment by Shardinara** [comment]
http://coriolis.io/outfit/cobra_mk_iii/04D4E4D3E3D3D4C----000349---2h24.Iw1-kA==.Aw1kIxWFA===?bn=Pandora,  this is the Coriolis build. ill try to get in game now.

**Comment by Shardinara** [comment]
![screenshot_0000](https://cloud.githubusercontent.com/assets/16336215/11884469/c02b5e64-a565-11e5-8e24-ff20a9904ae1.jpg)
![screenshot_0001](https://cloud.githubusercontent.com/assets/16336215/11884472/c3856e7e-a565-11e5-9114-1c04ef114b69.jpg)

I a little new to this hope its what needed. shows 7,38MW

**Comment by cmmcleod** [comment]
Hmm I'll have to investigate in-game. If you want to help you can look at the power difference for each module (in-game vs coriolis). I'll have a look later tonight

**Comment by Shardinara** [comment]
Cool thanks for your time, I'm a bit tied up today but will look further into it tomorrow.

**Comment by Shardinara** [comment]
Hiya i had a preliminary look and the discrepancy, it is in the thrusters on this ship/load-out anyway. FD may have adjusted for some reason, possibly they lowered thruster power requirements to offset SRV parking module, this would help to not upset peoples power starved finely balanced builds. hope this info helps i don't own any other ships to test so that's about all i can say,  Thanks for your time. and hope you stick with this very helpful program.

**Comment by Shardinara** [comment]
Just to be more specific 4E thrusters Coriolis 33.6% of 11.7mw
                                              1.5/2.0 in game   28% of 11.7mw

That would about account for the 0.54mw discrepancy.

**Comment by cmmcleod** [comment]
Thanks for the info. Closing this in favour of creating a specific issue addressing this
