### ISSUE TITLE
Detailed Discovery Scanner Power Consumption

### ISSUE THREAD

**Issue by Riboflavinator** [cmmcleod/coriolis#132]
This is not being counted as a component for power consumption.

Detailed - 0.60pwer

**Comment by cmmcleod** [comment]
You mean Detailed Surface scanner?

Do you have screenshots? I tested this (in great detail) pre 1.5 and the detailed surface scanner didn't use any power (despite reports to the contrary). This may have been 'fixed' in 1.5/2.0. 

Screenshots of ship power management or the outfitting screen would be greatly appreciated

**Comment by Riboflavinator** [comment]
Ah yes, just got home. Here's a few screenshots for you.
![power1](https://cloud.githubusercontent.com/assets/16359722/11915792/3c2e9948-a685-11e5-9dc9-645818d017e1.jpg)
![power2](https://cloud.githubusercontent.com/assets/16359722/11915793/3c31d1e4-a685-11e5-8b29-5c1a8905327b.jpg)
![power3](https://cloud.githubusercontent.com/assets/16359722/11915794/3c33826e-a685-11e5-887e-0159dc193ee4.jpg)

**Comment by Riboflavinator** [comment]
I guess I could have just taken a snapshot of this as well....
![power4](https://cloud.githubusercontent.com/assets/16359722/11915807/8e321f76-a685-11e5-8e20-e7eb779166b1.jpg)

**Comment by cmmcleod** [comment]
After testing the Detailed Surface scanner still does not use power (Just like the Basic or Advanced Discovery Scanner).

As you can see from the image below it uses 0% (not 3% or 3.8% that is actually uses).

![screenshot_0001](https://cloud.githubusercontent.com/assets/823967/11916831/6ce5577a-a69e-11e5-8cb6-98d57821ce67.png)
