### ISSUE TITLE
Ship model selection page cuts off last entry on Safari 9.0.2 (OS X)

### ISSUE THREAD

**Issue by MaineQat** [cmmcleod/coriolis#133]
On Safari 9.0.2 on OS X, the last entry entry (the Vulture in default sort) in list of ships and statistics is covered up by the scroll bar, with only the very top row of pixels showing.

**Comment by cmmcleod** [comment]
This is a known issue with Safari on OSX when the 'Always show scroll bars' is turned on.

When this option is turned on Safari sometime does not add additional space for the scrollbar. Reloading the page sometimes helps.

Alternatively this can be turned off under System Preferences -> General -> Show scrollbars -> When scrolling.
