### ISSUE TITLE
Cobra mk III 30k price reduction

### ISSUE THREAD

**Issue by Shardinara** [cmmcleod/coriolis#134]
I think the Cobra iii has had a 30k price reduction, exactly 30k off the hull can anyone confirm im at mach city in Yimanbin system, all other ships are correctly priced no discounts running, new price is 
349,718cr.

**Comment by cmmcleod** [comment]
Thanks for letting me know. Fixed in 1.10.3

**Comment by Shardinara** [comment]
Thank You.
