### ISSUE TITLE
Orca top 2 internal slots not working?

### ISSUE THREAD

**Issue by smartroad** [cmmcleod/coriolis#135]
I can't afford an Orca to test but the top two slots in the Orca's page only show cargo racks and hull reinforcements nothing else.

Just thought I would mention :grin:

**Comment by Shardinara** [comment]
Sorry to butt in but i think that's as intended, the orca is a special case with some cargo restrictions.

**Comment by cmmcleod** [comment]
@Shardinara you are correct. The Orca is a special case where the top 2 slots can only use Cargo Racks, or Hull reinforcements (at this point in time).
