### ISSUE TITLE
Detailed Surface Scanner 0.6 power draw not calculated

### ISSUE THREAD

**Issue by QV** [cmmcleod/coriolis#136]
When equipping the DSS it doesn't include the 0.6 power draw into the total calculation.

**Comment by Shardinara** [comment]
It does not draw any power, it says it uses .60mw but it does not actually use any power, sort of a bug in the game. The Coriolis tool is an accurate. also for reference see closed issue #132

**Comment by QV** [comment]
Ah ok didn't know this, thank you for quick follow up
