### ISSUE TITLE
Introduce "Rename" button

### ISSUE THREAD

**Issue by QV** [cmmcleod/coriolis#137]
Currently "Save" works counter-intuitive as the UI suggests you can rename a build but this is not supported as it always will create a new build.

Feature request to adapt code so that new button is added called "Rename" only activate when an existing build name is being edited and the "Save" button becomes greyed out (or replaced if there is an ng-appear/ng-disappear equivalent for "ng-disabled").

If you think it's a good idea I've looked at the code and I might give it a shot: add button in page-outfit.html, change js function of bnChange(), etc

**Comment by cmmcleod** [comment]
Yeah this is something I've been meaning to redo for a while.

There are 2 cases:
 - `Save` - Save the current build under it's existing name (no name change)
 - `Save As` - Save a copy of the build under the new name (name change)
 - `Rename` - Rename the current build and save under new name (name change)
 - `Overwrite` - The new name already exists as a different build, overwrite using current build (name change)

In the event a name already exists only Overwrite would be shown.

As a part of these changes I also want to add a drop-down list of current build names (for the Ship type).

**Comment by cmmcleod** [comment]
Released - Beta
