### ISSUE TITLE
Imperial Eagle module power draw

### ISSUE THREAD

**Issue by Mysturji** [cmmcleod/coriolis#138]
The actual power draw for the Imperial Eagle exceeds the stated draw on Coriolis.io
See the following build:

http://coriolis.io/outfit/imperial_eagle/03A3B3A1D2A2D2C270p0p0l406b4v4v.Iw1-EA==.EwBhEYy6GYyA?bn=Joe%20HIMEOBS%20Walsh
In coriolis, the FSD is still powered on with hardpoints deployed, but in-game it is not.

Same issue with 2x 1A SCB's: coriolis says FSD, cargo hatch & FSD Interdictor are offline, but in-game, everything goes offline when hardpoints are deployed.

**Comment by cmmcleod** [comment]
Can you please provide screenshots of your modules / power management section in-game?

**Comment by cmmcleod** [comment]
The SCB listed in the build are 1B not 1A. Also the Thruster in the build is B rated, which is unusual, are you sure you are not using an A rated Thruster?

Please post screenshots of your modules screen in-game.

**Comment by Mysturji** [comment]
Hi Colin
I'm out in the black now, so I can't provide screenshots. I tried 1A scb's, and when they used too much power in-game, I tried 1B's with similar results. I think I downgraded the thrusters in an attempt to get a workable build. 
The modules in the coriolis build I submitted in the report were accurate for the last build I tried before dumping one of the scb's

Cheers
Gordon

**Comment by cmmcleod** [comment]
Even if you are out in the black you can still take pics of this:
![Power Management](http://vignette3.wikia.nocookie.net/elite-dangerous/images/f/f5/Module_priority_control.png/revision/latest?cb=20150505004536)

**Comment by Mysturji** [comment]
I'm exploring the lagoon nebula in my asp. 😀
I don't think a screenshot would help. 😉

**Comment by cmmcleod** [comment]
Ah :S
