### ISSUE TITLE
Save Info to account (feature request)

### ISSUE THREAD

**Issue by Zeolish** [cmmcleod/coriolis#140]
Hi, love the work on Coriolis. :+1: 

I use this at work (on my lunch break) and have to keep copying and pasting the links into a notepad and saving that onto my cloud then opening it back up and looking at it at home where the game is. 

Any chance of just storing the saved data on the account as opposed to in cookies on the local machine? 

Many thanks, 
CMDR Zeoli

p.s. dunno how to add the label "Feature Request"

**Comment by freiheit** [comment]
Zeolish, FYI, http://inara.cz/ has functionality to save coriolis.io data in an account (using coriolis.io "export" and copy-paste.)

**Comment by Zeolish** [comment]
That is handy. and I did not know about the website. Thank you.

**Comment by cmmcleod** [comment]
Saving your account + builds, etc is coming. There is an existing issue tracking this - #12 

Closing in favor of #12
