### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Shardinara** [cmmcleod/coriolis#141]
Is there a way to have more than one instance of the app running a one time on the same machine.
I have some ships with discount some without, looking for a workaround to the universal ship discount selection,
Or is it possible to have the discount specific to each ship at the same time.
Thanks for your time.

**Comment by Shardinara** [comment]
I thought of a better way of putting it as a feature request, could the discount setting be set in the specific ship build rather than at the App settings level, i,m not going as far as asking for each module to have the setting just each complete build.
Hate to be a bother but after all you are going to live forever.

**Comment by cmmcleod** [comment]
Right now this is not possible, although you could use 2 separate browsers each with their own discount settings, however this is not a practical workaround.

Having build-specific discount overrides would be a good feature to add. I will create a separate issue to track this

**Comment by cmmcleod** [comment]
Closing in favor of #142
