### ISSUE TITLE
Reload cost of AFMU ammunition 100 times too high

### ISSUE THREAD

**Issue by Izack** [cmmcleod/coriolis#143]
The reload cost is indeed given as 100cr in the station menu, but in game this supplies 100 units of ammunition, while Coriolis considers it 100cr per unit. Basically, the unit price for AFMU ammo should be 1 in Coriolis, not 100.

Thanks for this excellent tool, by the way.

Regards,
Cmdr Coalwalker

**Comment by cmmcleod** [comment]
Thanks for the report. Will fix!
