### ISSUE TITLE
Anaconda: Explorer template

### ISSUE THREAD

**Issue by angushawk** [cmmcleod/coriolis#144]
Class 3 shields are not sufficient for default exploration weight. 

Suggest increasing to class 4 or higher.

**Comment by cmmcleod** [comment]
There isn't a template, but rather a procedure which picks the lightest possible shields. 

I certainly agree that 3D Shields might be insufficient for planetary landings with an explorer conda, the point of the explorer build 'template' / procedure is to optimize jump distance. It's trivial for a user to select better shields if necessary.

**Comment by angushawk** [comment]
Noted, however, those shields will not activate. Better to have none, than to add useless weight.

Thanks for the time.

Sent from my iPhone

On Jan 17, 2016, at 23:23, Colin McLeod <notifications@github.com<mailto:notifications@github.com>> wrote:


There isn't a template, but rather a procedure which picks the lightest possible shields.

I certainly agree that 3D Shields might be insufficient for planetary landings with an explorer conda, the point of the explorer build 'template' / procedure is to optimize jump distance. It's trivial for a user to select better shields if necessary.

-

**Comment by atfrase** [comment]
Are you sure? Class 3 shields have a maximum hull mass of 413T, and the Anaconda base hull mass is 400T. If class 3 shields can't be installed on an Anaconda, that's news to me.

**Comment by angushawk** [comment]
The D rated sensors alone weigh 64 tons.

The explorer template Anaconda has a weight of 529. If the class 3 shields can be function, I'd be amazed. I have been wrong before though.

Sent from my iPhone

On Jan 18, 2016, at 07:27, Alex Frase <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you sure? Class 3 shields have a maximum hull mass of 413T, and the Anaconda base hull mass is 400T. If class 3 shields can't be installed on an Anaconda, that's news to me.

On January 18, 2016 1:28:46 AM CST, angushawk <notifications@github.com<mailto:notifications@github.com>> wrote:
>Noted, however, those shields will not activate. Better to have none,
>than to add useless weight.
>
>Thanks for the time.
>
>Sent from my iPhone
>
>On Jan 17, 2016, at 23:23, Colin McLeod
><notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
>
>
>There isn't a template, but rather a procedure which picks the lightest
>possible shields.
>
>I certainly agree that 3D Shields might be insufficient for planetary
>landings with an explorer conda, the point of the explorer build
>'template' / procedure is to optimize jump distance. It's trivial for a
>user to select better shields if necessary.
>
>-
>Reply to this email directly or view it on
>GitHub<https://github.com/cmmcleod/coriolis/issues/144#issuecomment-172448827>.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cmmcleod/coriolis/issues/144#issuecomment-172449843


-

**Comment by cmmcleod** [comment]
The 3D Shield Generator does function. Only hull mass affects Shield Strength (not unladen or laden mass). This is a known game mechanic (in addition to this I also have an explorer conda with 3D shields).

**Comment by Shardinara** [comment]
Let me explain it, with regard to shields the max hull size is referring to the volume of the hull not the weight, so a 400t Hull is a certain volume that the shield can spread over, so its irreverent how much mass you pack into that space, hence only the base hulls mass having effect on your shield capability. so for shields at least max hull is really max Volume which does not change with more weight within the fixed area of the hull.
Hope this helps.

**Comment by angushawk** [comment]
I see it now. Thanks much.

Helps with my future builds as well!

Keep up the good works.

Sent from my iPhone

On Jan 18, 2016, at 22:26, Shardinara Cry <notifications@github.com<mailto:notifications@github.com>> wrote:


Let me explain it, with regard to shields the max hull size is referring to the volume of the hull not the weight, so a 400t Hull is a certain volume that the shield can spread over, so its irreverent how much mass you pack into that space, hence only the base hulls mass having effect on your shield capability. so for shields at least max hull is really max Volume which does not change with more weight within the fixed area of the hull.
Hope this helps.

-
