### ISSUE TITLE
Orca Limited Internal slots 5 and 6

### ISSUE THREAD

**Issue by Uriei** [cmmcleod/coriolis#145]
For some reason, when trying to fit an Orca, the class 6 and one of the class 5 slots are limited to only Cargo racks and Hull Reinforcement Packages.

Normal class 5 slot: https://i.gyazo.com/83c74af5ca76359a966154d90f642642.png
Limited class 5&6 slots: https://i.gyazo.com/df2db64f2b8e2d4dcbfdd68163ed4444.png

**Comment by cmmcleod** [comment]
Ah yes the Orca... This is correct. The Orca's top two slots can only mount Cargo Racks and HRPs.. Presumably it will also be able to mount passenger modules when the time comes...
