### ISSUE TITLE
Slash (Hex 2F) in build name is double-encoded.

### ISSUE THREAD

**Issue by Athanasius** [cmmcleod/coriolis#148]
A simple slash character '/' is encoded not as %2F, but as %252F, i.e. / becomes %2F becomes %252F (the % symbol is hex 25).

Changing this to simply %2F does appear to work, i.e. my browser, and your server, hasn't decided to treat it as a straight slash and interpret it as a path separator.

I came across this due to work on my IRC bot's URL parsing, wanting to pull build names out of coriolis.io URLs, and then wanting to decode the % encoding.  Right now I'm having to hard-code a check for %252F to replace it properly.

**Comment by cmmcleod** [comment]
Just to confirm the / characters are only in the build name?

**Comment by Athanasius** [comment]
Yes, for this URL parsing I'm not even fetching anything.  Ship name out of the URL path component, and build name out of the ?bn=... bit.

I have a build called "Anaconda - Max Jump/SC Range", which has the URL http://coriolis.io/outfit/anaconda/02A6D6A5D5A8D5C------------------------322i2f.AwRjOV2ndyRA.Aw18ZlA=?bn=Anaconda%20-%20Max%20Jump%252FSC%20Range

Reproduced with blanking the name then re-saving as: http://coriolis.io/outfit/anaconda/02A6D6A5D5A8D5C------------------------322i2f.AwRjOV2ndyRA.Aw18ZlA=?bn=bibble%252Fbobble

**Comment by cmmcleod** [comment]
Great, just wanted to confirm it wasn't something else funky. Able to replicate the issue.

Will investigate and fix

**Comment by cmmcleod** [comment]
Found the issue. This will be fixed in 2.0
