### ISSUE TITLE
Drag & Drop Hardpoints and internal slots

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#15]
Drag a component from a slot to another eligble slot.

On Drag: Disable ineligible slots (grey out), highlight eligible slots (Greenish?).

**Comment by Maverick-JM** [comment]
Hey, if you've no objections I might start work on this. Looks interesting and reasonably straightforward :) (also useful). I'm thinking drag and drop will move a component, hold Ctrl to copy it?

**Comment by Toxicat** [comment]
> Holding nothing = swap, holding Ctrl = copy (and leave the original where it was), holding Shift = Move and leave previous spot empty.

Hum, and for mobile/tablet users ?

**Comment by Maverick-JM** [comment]
For those folks, I was thinking they would just have the swap option (that one seems the most useful).

Not sure what else we could really do there.
________________________________

**Comment by Toxicat** [comment]
Sounds logic

**Comment by cmmcleod** [comment]
@Maverick-JM Feel free to take a stab at this!

I would suggest skipping the CTRL + drag to copy, at least to begin with. The plugin if used for drag and drop (which support exactly what we would need) is in use on the comparison page in the compare / facet selection section.

The plugin and documentation can be found here: https://github.com/a5hik/ng-sortable

My experience with it has been great so far.

**Comment by cmmcleod** [comment]
@Maverick-JM If you want to work on 'higher priority' tasks, you can find them here:

https://github.com/cmmcleod/coriolis/labels/ready

Or get an overview here: https://waffle.io/cmmcleod/coriolis

**Comment by Maverick-JM** [comment]
Been busy with other stuff, but I've started actually looking at this now :).

**Comment by cmmcleod** [comment]
Released - Beta
