### ISSUE TITLE
Feature Request: More Granular or Custom Discount options.

### ISSUE THREAD

**Issue by WEKarnesky** [cmmcleod/coriolis#150]
With the current Community Goal reward there is a 30% discount and the 2.5% for each elite ranking discount there are multiple  discount options that aren't available.  A possible fix would be a slider control or number box with a higher top end to account for the other options.

**Comment by cmmcleod** [comment]
Yeah, I think a text-field is necessary at this point.

As a side question: Are you sure Elite rank discounts stack? I.e. double Elite - 5%, tripple Elite - 7.5%?

**Comment by WEKarnesky** [comment]
I can't independently verify this right now, I don't quite have any elite rankings.  I am told it stacks with everything, so triple elite plus founder's world is 17.5% off.  [Here is a reddit post I found that I as basing this off of.](https://www.reddit.com/r/EliteDangerous/comments/42t8cn/what_all_does_combattradeexplorationcqc_rank/czcwkrz)

**Comment by cmmcleod** [comment]
I'm double Elite (haven't really checked prices since I was single Elite) so I'll check later tonight

**Comment by Uriei** [comment]
A text-field is the way to do it, but not only for discounts, now "i Sola Prospect" has 20% increases price, no actual option works for that.

**Comment by cmmcleod** [comment]
Released - Beta
