### ISSUE TITLE
Imperial Courier Weight is slightly Off

### ISSUE THREAD

**Issue by Razgriz-III** [cmmcleod/coriolis#151]
The weight for the Imperial Courier seems to be off slightly. First noticed it on this build http://coriolis.io/outfit/imperial_courier/03A3A3A1D3A2D3C27270s070700002t4001010166.Iw18UA==.IwBhrSvTmI==?bn=Light%20Courier.
Coriolis lists the unladen and laden masses as 76.9 and 96.9, though those do not add up with the cargo capacity. In game is listed as 84.1 and 96.1.
![Image](https://cloud.githubusercontent.com/assets/13974257/12969822/31e0f9f6-d054-11e5-9717-aca39be87a30.png)

**Comment by cmmcleod** [comment]
Can you please provide screenshot(s) of your internal modules?

**Comment by cmmcleod** [comment]
Laden Mass = Unladen Mass + Fuel + Cargo

**Comment by cmmcleod** [comment]
Are you sure you aren't using a 1D Frame Shift Drive Interdictor in-game?

If you are, all of the numbers add up correctly.

**Comment by Razgriz-III** [comment]
Sorry, it is a 1D FSD Interdictor. Also, my mistake, I thought that the unladen mass would include a full tank.

**Comment by cmmcleod** [comment]
No worries. I'm adding tooltips to the next version so this should be clearer
