### ISSUE TITLE
Coriolis broken in Chrome

### ISSUE THREAD

**Issue by rcthelp** [cmmcleod/coriolis#152]
As of yesterday around midday (UTC) 12-Feb, Coriolis no longer renders in my version of Chrome.

Windows 7 Pro, 64-bit
![image](https://cloud.githubusercontent.com/assets/8623605/13026881/5bb2051c-d230-11e5-987f-52e6fb33e3e3.png)

It's possible that this may be a Chrome issue as (for example) Facebook is not working correctly for me either.

Chrome is 'up to date' Version 48.0.2564.109 m

**Comment by Piehthyte** [comment]
May only be you, I do not have that problem at all. Try clearing your cache?

http://i.imgur.com/CsTKr1B.png

**Comment by rcthelp** [comment]
Thanks. Clearing caches has fixed it. Please close this non-issue.
