### ISSUE TITLE
Imp Eagle manufacturer

### ISSUE THREAD

**Issue by marcusstratus** [cmmcleod/coriolis#155]
Last I checked I thought the Imperial Eagle was manufactured by Gutamaya, not Core Dynamics. Just noticed this when I sorted the Coriolis list by  manufacturer

**Comment by cmmcleod** [comment]
Are you sure?

http://elite-dangerous.wikia.com/wiki/Imperial_Eagle

![Eagle Comparison](http://nosuchwebpage.com/pics/Pilots_Guide/eagle_vs_eagle2.jpg)

**Comment by cmmcleod** [comment]
Some supporting Lore:

> It's a Gutamaya upgrade of a Core Dynamics ship. As an Imperial ship upgraded by Imperial shipwrights, I am pretty sure neither party would let the Federal Navy's main supplier take credit for it.
> At the very least, it's manufactured by Gutamaya in an Imperial shipyard, even if the design was originally based on a Core Dynamics blueprint.

**Comment by marcusstratus** [comment]
Haha! Last I checked was back in November '15. hmmm... I wonder if that's
something FD neglected to change. There was a time when the hologram of the
Imperial Eagle was the same as Federal.

**Comment by cmmcleod** [comment]
closing for now
