### ISSUE TITLE
hatch breaker limpet controller mass error

### ISSUE THREAD

**Issue by ixty** [cmmcleod/coriolis#156]
Hello,

There is a problem with the weight of (at least) 3A hatch breaker controller.
Its weight in coriolis is 0 whereas in game it weights 8T.

Just letting you know cause i was bugged out by my ingame ship range being different from coriolis.

Thanks for your work,

**Comment by cmmcleod** [comment]
Turns out I'm missing the mass for all Hatch breaker limpets. Will fix!

Very surprised no one has caught this until now since this has been an from day one.

**Comment by cmmcleod** [comment]
Fixed in 2.0-Beta-3
