### ISSUE TITLE
Compare tool shows incorrect boost speed for builds incapable of boosting

### ISSUE THREAD

**Issue by compro01** [cmmcleod/coriolis#157]
If you load a build into the compare tool that is not capable of boosting (i.e. explorer build), the comparison chart and "speed" graph still give numbers as if it was capable of boosting

Both of the ships in this comparison are explorer builds with 1D distributors.  It should display 0 for the boost speed, as it does in the main build display.

![Screenshot illustrating issue](https://cloud.githubusercontent.com/assets/2030521/14237878/2460d35c-f9e7-11e5-99ad-77fe4583bb1b.jpg)

**Comment by cmmcleod** [comment]
Good catch. Will fix

**Comment by cmmcleod** [comment]
Fixed in 2.0-Beta-3
