### ISSUE TITLE
Only cargo racks and HRPs on Orca's upper 6 and 5 slots, can't fit anything else.

### ISSUE THREAD

**Issue by ivanquirino** [cmmcleod/coriolis#158]
Can't fit anything than Cargo racks and Hull Reinforcement packages on the 6 and 5 upper slots in a Orca. Other slots are fine.
http://coriolis.io/outfit/orca/05A6A5A6D5D4D4C-1717------------.Iw18SQ==.Aw18SQ==

**Comment by cmmcleod** [comment]
That is correct. The Orca first 2 slots are special and cannot mount other module types.
