### ISSUE TITLE
Power Priorities not changing

### ISSUE THREAD

**Issue by BeBumble** [cmmcleod/coriolis#159]
The last couple of days I have been trying to change the power priorities on my ship builds but when I click on the arrows nothing changes.

I've cleared the cache on my browser (Chrome) but still cant change the power priorities

**Comment by cmmcleod** [comment]
Were you using http://coriolis.io or https://coriolis.io? What version of Chrome do you have?

No code changes have been released for several weeks. When did this start happening?

**Comment by BeBumble** [comment]
Using Chrome version  49.0.2623.112 m

I switched to https:// and looks to be working fine, before here was no http: or https: prefix but i've never had a problem til a few hrs ago. Havent changed a thing here, very odd


On Wednesday, 27 April 2016, 15:51, Colin McLeod <notifications@github.com> wrote:



Were you using http://coriolis.io or https://coriolis.io? What version of Chrome do you have?
No code changes have been released for several weeks. When did this start happening?

**Comment by cmmcleod** [comment]
Interesting. https://coriolis.io is the latest / new version (2.0) and you should be using that from now on. So I'm glad that works. I'll be shutting down 1.0 / http://coriolis.io this week
