### ISSUE TITLE
Thrusters enhance top Speed/Boost

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#16]
Thursters can improve top speed/boost it seems. 
Data and model/function needed to implement

**Comment by Toxicat** [comment]
Thrusters improve (or decrease, in case of downgrade) agility too.

**Comment by Psieonic** [comment]
I haven't seen any mathematics for any of it yet; but based on my own testing, it seems as if the agility bonus for having a better-than-optimal load-out only improves agility indirectly, by increasing top speed therefore marginally increasing the size of the 'blue zone' that allows higher manoeuvrability. Having a worse-than-optical configuration penalises you however.

Any improvements to agility are marginal at best. The top speed and boost speed improvements however are quite tangible. (For example; a Cobra Mk III being capable of going 435 m/s boosting with 4A thrusters.)

**Comment by iLikeCookiesQ** [comment]
higher mass also makes your ship slower. (is that even the case?) is there any mathematical model that defines this?

**Comment by cmmcleod** [comment]
I believe mass vs thurster optimal mass affects top speed (seems fairly obvious). No model exists yet. More data is required

**Comment by cmmcleod** [comment]
Using a following [Google Doc Form](https://docs.google.com/a/mcleod.eu/forms/d/1qEQjpSiiROzJD0cDOwON31d8zIXNboVrr4wF0oSXfUI/viewform) to gather data.

[E:D Forum Post](https://forums.frontier.co.uk/showthread.php?t=157834&p=2411416#post2411416)

[Reddit post](http://www.reddit.com/r/EliteDangerous/comments/3a3ab7/crowdsourcing_ship_speeds_for_thruster_x_with/)

**Comment by cmmcleod** [comment]
Confirmed that mass affects ship speed and agility.

Another forum discussion here: https://forums.frontier.co.uk/showthread.php?t=146312&page=2&p=2457743

**Comment by cmmcleod** [comment]
Spreadsheet / Data publicly available here: https://docs.google.com/spreadsheets/d/1Ki4zycw2jdGJYgW90xL22ehAJb71YDFtXdzBClnpBUg

**Comment by gryphus1153** [comment]
I'm not sure if you've seen this, but I was doing some googling and came across this post which details speed to mass ratios and it's effect on turn rate, boosting and speed. 
https://forums.frontier.co.uk/showthread.php?t=164931

It also links to some very relevant info about thrusters (pips & also additional data for mass) from other people as well.
I'm unsure of it's accuracy, but it seems to corroborate with some of the results in your spreadsheet as well as some others from the links linked.

Mass to Performance ratio TL;DR:
- There's a **minimum mass** (50% of Optimal Mass) where reducing mass further doesn't further increase performance.

- The **Performance increase** as mass decreases is wholly dependent on the rating of the thruster. not the class or ship. (The percentage increase also differs from rating to rating. i.e @ 50% mass/optimal mass, A class: 16% increase whereas E Class: 3% increase)

- The performance increase as mass decreases is non-linear. (His results correlate with those on your Hauler chart)

- The performance increase of turn rate and speed are both affected by the **same amount**

**Comment by cmmcleod** [comment]
Yeah I have looked into it/following this thread. I'm hoping I or someone else will figure it out soon. We are getting close!

**Comment by Cliffson** [comment]
Hi

I have uploaded the relevant parts of my thruster testing here:

https://docs.google.com/spreadsheets/d/1CKKvrXOqjuA1WLSnJ12CaI7FrEM-3QaUR6ynGsLm95c/edit#gid=0

No boost speed measurements I'm afraid but anecdotally the ~16% increase at A(50%) seems to hold for boost speeds (Clippers get up to 440, cobra's up to 464 etc)

**Comment by inorton** [comment]
Hiya, I've been using your data and thinking out loud here - https://plus.google.com/+IanNorton/posts/6SgEUzUBtvz

I've also added 65.3t 2A thrusters for Hauler, Sidewinder and Eagle to my copy of the sheet

**Comment by spullara** [comment]
Looks like this research should help a bunch:

https://forums.frontier.co.uk/showthread.php?t=182057

**Comment by cmmcleod** [comment]
Just saw this myself. Excellent. Looking into implementing this now
