### ISSUE TITLE
Settings misaligned on Firefox [2.0.0-Beta-3 - 2016-04-04]

### ISSUE THREAD

**Issue by Phillipus** [cmmcleod/coriolis#163]
Not sure if you want bug reports for the beta version but here it is anyway.

2.0.0-Beta-3 - 2016-04-04
Firefox 46
Mac and Windows

The settings values are misaligned

![screen shot 2016-04-30 at 11 17 53](https://cloud.githubusercontent.com/assets/600504/14935333/8ea02cac-0ec5-11e6-85fa-135686076ea3.png)

**Comment by cmmcleod** [comment]
Yes, definitely want bug reports for 2.0.0 Beta. Will fix!
