### ISSUE TITLE
Jameson Memorial module discount is 12.25% ?

### ISSUE THREAD

**Issue by Athanasius** [cmmcleod/coriolis#164]
Assuming the base prices in coriolis.io (Version 1.10.5 - 2016-03-01) are correct I'm see a 12.25% discount at Jameson Memortial in Shinrarta Dehzra.  It would be convenient if I could set that value in the coriolis.io options.

Example (that should be easy to find elsewhere): 3D Power Distributor costs 8892 credits.
Example (high price): 7D Power Distributor costs 546546 credits.

**Comment by Athanasius** [comment]
Checking ship prices at Liwei Terminal in GD 140, where I have no reputation (absolutely neutral) with the owning minor faction, and 19% Neutral with the Federation (that they're affiliated with), I'm seeing that the Shinrarta Dehzra ship prices are indeed 90% of these normal ones.

**Comment by Athanasius** [comment]
And the same holds for 3D Power Distributor, costing 9880 credits at Liwei Terminal.  That puts the Shinrarta Dehzra price at 90%.  There's no 7D Power Distributor here to compare that.

So, does coriolis.io just have incorrect base prices of ships and modules ?  Or this this because I'm a Premium Beta commander and that is somehow throwing prices off ?

**Comment by Athanasius** [comment]
Ah, apparently there's every chance this is the Elite rank discount (I have Elite in Explorer).  Looks like that's 2.5%.  Someone else has confirmed 3D Power Distributor, on a plain ED account (no alpha/beta) as 10113, and Viper Mk IV at 437931.  The prices I see at Liwei are 97.5% of those.  Then when I go to Shinrarta Dehzra I see 90% of /those/ prices.

So for someone with at least one Elite Rank at Shinrarta Dehzra it's price * 0.975 * 0.9, or a 12.25% total discount.

**Comment by cmmcleod** [comment]
You get 2.25% discount for being Elite (unfortunately it doen't stack with double or tripple Elite).

You should be using / move to https://coriolis.io (note the HTTPS). This is where version 2 is hosted and you can enter variable discounts (e.g. 2.25, or 1.23, etc)

**Comment by Athanasius** [comment]
I did spot that the github code seemed to be ahead of what was published "on the site".  Have you thought about at least updating the http-only version to have a banner saying the latest is on https-only ?  Then there's redirects and HSTS headers you could use as well....

I'm pretty sure the Elite is 2.5% alone, as that's what I saw when NOT at Jameson Memorial.  Just the way it stacks then makes the total at Jameson 12.25% (as you then only take another 10% off the already 97.5% price).

**Comment by colin-air** [comment]
As for the HTTP / HTTPS issue - Yes, everything will redirect, etc, except http://coriolis.io/ (which will have appropriate messaging). I simply haven't gotten around to it yet.

As for the discounts - that definitely makes sense, it is multiplicative rather than additive.
