### ISSUE TITLE
Error when trying to change module

### ISSUE THREAD

**Issue by lausianne** [cmmcleod/coriolis#166]
It's my fault, in a way, but maybe the system could be more forgiving ...

I had a FDS and would like to copy the loadout to my FAS. So I simply changed "federal_dropship" to "federal_assault_ship" in the URL. Seems to work fine at first, but there is a gun in a utility slot. When trying to change that, I get the error.

Thanks for your great site!

Cheers, Ralf.

Browser:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Path:
/outfit/federal_assault_ship/06A6C5A5D6A4A4C0v1l1l1l1l0404000k5n4a043302252f.Iw18aQ==.Aw18aQ==
Error:
unknown
Message:
Cannot read property 'offsetTop' of undefined
Details:
TypeError: Cannot read property 'offsetTop' of undefined
    at link (http://coriolis.io/app.dced5e7d.js:26:1756)
    at http://coriolis.io/lib.792f04d9.js:7:2274
    at ea (http://coriolis.io/lib.792f04d9.js:7:2331)
    at D (http://coriolis.io/lib.792f04d9.js:6:28674)
    at g (http://coriolis.io/lib.792f04d9.js:6:25046)
    at D (http://coriolis.io/lib.792f04d9.js:6:28618)
    at g (http://coriolis.io/lib.792f04d9.js:6:25046)
    at http://coriolis.io/lib.792f04d9.js:6:24687
    at http://coriolis.io/lib.792f04d9.js:6:25531
    at k (http://coriolis.io/lib.792f04d9.js:6:27857)

**Comment by colin-air** [comment]
I agree the error handling could be better, I'll have a think about how best to handle this kind of error

**Comment by lausianne** [comment]
Thanks! Nothing urgent, just a minor inconvenience ....
