### ISSUE TITLE
Updates from 2.1/1.6

### ISSUE THREAD

**Issue by nomadyow** [cmmcleod/coriolis#167]
2.1/1.6 introduces new Hardpoints that would be nice to get into Coriolis

Huge Lasers and Multi Cannons, etc.

**Comment by cmdrklepto** [comment]
Yes. It's already available at ED:Shipyard with all tech data

**Comment by cmmcleod** [comment]
Data has been pulled in. Running through some testing and minor issues (handling special cases for new / ehnanced thrusters).
