### ISSUE TITLE
Incorrect ammo for 2B/FD Missile Rack

### ISSUE THREAD

**Issue by Jazz-fr** [cmmcleod/coriolis#169]
In 2.1 release 2B/FD Missile Racks were updated to have 60 rockets in total per unit, 12 preloaded, plus 48 in "spare magazines". Have not checked other missile launchers, but their ammo sizes could've changed as well.

**Comment by Precursorx** [comment]
seems to be worth to recheck all the ammo values heatsinks are also wrong

**Comment by cmmcleod** [comment]
Fix will be in the next release
