### ISSUE TITLE
Power Distributor required for boost

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#17]
Disallow or at the very least warn players if they pick a PD that is not powerful enough to boost.

Data Need: MJ for Boost (based on Thrusters)

**Comment by Toxicat** [comment]
It would appear that the thruster need at least one inferior class of power distributor. Ex : 7D Th need at least 6D PD. More test are needed of course but it's a first step.

**Comment by cmmcleod** [comment]
Forum post here:
https://forums.frontier.co.uk/showthread.php?t=148222

Spreadsheet Tracking info here:
https://docs.google.com/spreadsheets/d/1THIQPq84LEAMBDswKqlQDVc0TXHBq30Saz1Mb67JvBE/edit?usp=sharing
