### ISSUE TITLE
Builds not saved on Safari iPad iOS 9.3.2

### ISSUE THREAD

**Issue by greenkr** [cmmcleod/coriolis#170]
Created a build for Corvette on new edition, including huge mc. Gave a title, clicked on save icon then on save - nothing happened - save icon remained the same, build did not appear.

**Comment by woodbane** [comment]
Works absolutely fine on my iPad Air running 9.3.2

**Comment by woodbane** [comment]
I have noticed you almost seem to have to 'double tap' or press an icon twice quite quickly to get the action to happen though.

**Comment by colin-air** [comment]
This may be an issue with hover state (I will investigate and improve this!)

**Comment by woodbane** [comment]
Nice one.

**Comment by greenkr** [comment]
Tried the double tap on the save icon - it worked, thanks!

**Comment by cmmcleod** [comment]
The tooltips were causing a nuisance here, so I've disabled them on those buttons which resolves this issue. This fix will be in the next release
