### ISSUE TITLE
[Feature Request] Bring back ship name in title

### ISSUE THREAD

**Issue by Phillipus** [cmmcleod/coriolis#171]
In version 1, the title of each loadout web page included the ship's name, like "Anaconda - My Cool Loadout". Now in version 2 the title of a web page is "Outfitting - Anaconda". I save each loadout as a link, and this makes it harder to distinguish each ship unless I manually edit the title of each loadout,

Is it possible to re-instate the ship's name in the title?

(And, thank-you for your hard work!)

**Comment by colin-air** [comment]
Yes, definitely, not sure how I managed to miss that!

**Comment by Phillipus** [comment]
Excellent! Thanks. :-)

**Comment by cmmcleod** [comment]
Fixed. Will be in the next release

**Comment by Phillipus** [comment]
Nice. Thanks again.
