### ISSUE TITLE
Detailed Scanner Power Draw 0.60MW not calculated

### ISSUE THREAD

**Issue by MalikDama** [cmmcleod/coriolis#174]

**Comment by colin-air** [comment]
Previously the Detailed surface scanner never drew power, even though the interface claimed it draws 0.6MW. I tested this thoroughly.

I need to check to see if this is still the case in 2.1/1.6

**Comment by MalikDama** [comment]
yes it doesn't appear to draw power in the ship (tested it now off/on makes no difference
) only shows in outfitting screw
