### ISSUE TITLE
Lost all saves

### ISSUE THREAD

**Issue by AndrewdAzotus** [cmmcleod/coriolis#175]
The new version has lost contact with all my old saves

**Comment by colin-air** [comment]
Did you follow the steps at http://coriolis.io?

What is shown in the backup text field?

It should look something like

```
{
  "builds": {
    ...
  },
  "comparisons": {
    ...
  }
}
```

**Comment by AndrewdAzotus** [comment]
When I went to http://coriolis.io it was overridden to https://coriolis.io - I shall try again this evening [I'm using firefox]

**Comment by colin-air** [comment]
http://coriolis.io should not redirect

if it does you can go to http://coriolis.io/old-index.html

http://coriolis.io/[anything else] will redirect to https

**Comment by AndrewdAzotus** [comment]
Yes, sorry I must have just overriden the http with https hence it reverted. It's all better now ... saves restored - Thank you :)
