### ISSUE TITLE
Module sort order does not seem to be ordered

### ISSUE THREAD

**Issue by AndrewdAzotus** [cmmcleod/coriolis#176]
and when sorted does not seem to be saved

**Comment by colin-air** [comment]
Can you elaborate? Where are modules not sorted?

The sorted order is not saved when a page is reloaded or when you move from one ship to another

**Comment by dasimak** [comment]
I agree with the OP. Sorting is broken on https://coriolis.io
Repeatedly clicking on headers will not sort correctly. I tried sorting with a different field (ie priority) and then with the intended (power) but did not solve the problem.
I'm using firefox on win10.

**Comment by colin-air** [comment]
After some testing it seems that only power is sorted incorrectly, sorting by type, module name, and priority seem to work fine. (I've tested this in firefox, chrome, safari on OSX)

**Comment by dasimak** [comment]
Yes, you're right. I forgot to mention that I use sorting only on power (at least that's the only one that is useful for me). Sometimes (completely random), power get sorted correctly if another (random) field is sorted before it.

**Comment by AndrewdAzotus** [comment]
It's weird, with the old site it always seemed to be sorted by type and last night/this morning I could not get the site to remember. Now it seems to be fine and always displays modules sorted in type order.
