### ISSUE TITLE
The "Exploration" default build pulls 2D Power Plants.

### ISSUE THREAD

**Issue by ElanSolo** [cmmcleod/coriolis#177]
I believe that 2A was the default setting in the previous build and I not that some ships do still default to 2A, but the majority default now to 2D.

https://i.imgur.com/3Mirtmu.jpg

**Comment by cmmcleod** [comment]
Yes I suppose it should default to 2A, although the intention was always to maximize jump distance

**Comment by cmmcleod** [comment]
Will be fixed in the next release
