### ISSUE TITLE
Cannot use the page

### ISSUE THREAD

**Issue by styrwirld** [cmmcleod/coriolis#178]
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Path: /
Error: Unknown
Details:
scriptUrl: 
line: 1
col: 1697
error: {}
![untitled](https://cloud.githubusercontent.com/assets/19893232/15993041/6254eae4-30b1-11e6-8d97-93552e512a67.png)

**Comment by colin-air** [comment]
Can you provide more information? Can you provide the URL that this error occurs?

**Comment by styrwirld** [comment]
https://coriolis.io/

As soon as I enter, it loads correctly but 1 or 2 seconds after that, the
error appers in the middle of the screen and doesnt let me do anything.

On Sun, Jun 12, 2016 at 5:01 PM, Colin McLeod <notifications@github.com>
wrote:

> Can you provide more information? Can you provide the URL that this error
> occurs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmmcleod/coriolis/issues/178#issuecomment-225457115>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS-L8PVHenFKVy4MwbHz2isKa7IXL0kZks5qLGWDgaJpZM4Iz2dj>
> .
>



-- 
Mauricio Figueroa.

**Comment by styrwirld** [comment]
This issue was because of the UFT Add on for google chrome, once I uninstalled the add on it started working ok.

**Comment by cmmcleod** [comment]
Very odd.
