### ISSUE TITLE
Identify hardpoint positioning to the user

### ISSUE THREAD

**Issue by brumster** [cmmcleod/coriolis#180]
One (minor) feature I'd find useful would be some indication (ideally graphically) of where each hard point is positioned on each ship, to allow you to plan and spec the builds accurately. Particularly useful when you're trying to be specific about where to put a turret, for example, and sharing the link with others.

Potential issue around artwork of course. First iteration could consider just a text description of position maybe (front right, top left, bottom centre, etc)

**Comment by cmmcleod** [comment]
This has been requested many times, and it's not really a minor feature :P 

This probably won't be implemented until #160 is in progress / possible

**Comment by cmmcleod** [comment]
closing in favor of #160
