### ISSUE TITLE
error

### ISSUE THREAD

**Issue by the-mec** [cmmcleod/coriolis#181]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

Path: /outfit/python/0prtmFflidwssf51e1e7l2727040404004f5n050438v402C02f.Iw18eQ==.Aw18QLNJA===?bn=Budget%20Multi%20role%20Python

Error: Unknown

Details:

scriptUrl: https://coriolis.io/lib.79d7f1.js
line: 952
col: 18448
error: undefined

**Comment by colin-air** [comment]
Can you the provide steps that cause this error? Any details are greatly appreciated

**Comment by cmmcleod** [comment]
Please provide more information as I'm not able to debug this issue
