### ISSUE TITLE
3A Enhanced Performance Thrusters Stats Correction

### ISSUE THREAD

**Issue by Gerdofal** [cmmcleod/coriolis#182]
Stats for the 3A Enhanced Performance Thrusters are a bit off. Especially noticeable is power draw. Here are the full stats:

Class: 3
Rating: A
Mass: 5.00 T
Integrity: 55
Power Draw: 5.00MW
Boot Time: 0S
Minimum Mass: 70.0 T
Optimal Mass: 90.0 T
Maximum Mass: 200.0 T
Minimum Multiplier: 90%
Optimal Multiplier: 15%
Maximum Multiplier: 137%
Thermal Load: 1.3/s

For test purposes:
Eagle with total mass 78.6 T
Top Speed: 342 M/s
Boost Speed: 499 M/s

https://coriolis.io/outfit/eagle/0p0tzF5l3d3s8f2181i1i0k432o2f-.AwRj4yg=.CwBjEZJTwJhAzGIA?bn=Violet

**Comment by WEKarnesky** [comment]
I was coming here to log this as well.

**Comment by cmmcleod** [comment]
I will correct the data as much as possible.

Right now there is no accurate function to determine speed based on mass.

More info:
https://forums.frontier.co.uk/showthread.php/164931-Thrusters-explained-in-one-simple-table-(Rating-and-Mass)

**Comment by cmmcleod** [comment]
Power values will be fixed in the next release. Speed calculations are still unknown

**Comment by Gerdofal** [comment]
Greetings,

Here is the formula for calculations of speed based on ship mass and thruster type.

See this thread for reference: https://forums.frontier.co.uk/showthread.php/272013-Thruster-Speed-Formula-Need-some-data-to-refine-please?p=4246504#post4246504

The formula I'm using is a standard linear approximation formula:

When mass is below optimal:

Speed Multiple = Maximum Multiple + (Ship Mass - Min Mass) * ((Optimal Multiple - Maximum Multiple)/(Optimal Mass - Minimum Mass))

When mass is above optimal:

Speed Multiple = Optimal Multiple + (Ship Mass - Optimal Mass) * ((Minimum Multiple - Optimal Multiple)/(Maximum Mass - Optimal Mass))

A check must be made to make sure the result never goes above the Maximum Multiple or below the Minimum Multiple as defined by the thrusters.

Then multiply by base speed (230 in a Python).

All of my results are based on the values shown in the outfitter:

Mass is the left most number when given three numbers in the outfitter.

Speed is exactly as displayed in the outfitter

**Comment by EmanueleCiriachi** [comment]
Thank you for this, I was also trying to create a heavily engineer-modded Eagle with Enhanced Performance Thrusters and couldn't understand why they were less power-hungry than their 3A counterpart. Hopefully with fully engineered Power Generator it should be feasible!
