### ISSUE TITLE
Add FSD interdictor ranges

### ISSUE THREAD

**Issue by compro01** [cmmcleod/coriolis#184]
Referring to issue #2, we now have actual numbers for FSD interdictor ranges given in game.  They're specified in seconds.  Not light-seconds, but rather seconds at your current velocity  e.g. if you're moving at 1c, a 4A interdictor will have a reach of 16ls.

Below are the ranges for all classes and grades of interdictors.

Class/Grade | Range
----------------- | --------
1E|3s
1D|4s
1C|5s
1B|6s
1A|7s
2E|6s
2D|7s
2C|8s
2B|9s
2A|10s
3E|9s
3D|10s
3C|11s
3B|12s
3A|13s
4E|12s
4D|13s
4C|14s
4B|15s
4A|16s

**Comment by cmmcleod** [comment]
Thanks for the data! This is done and will be in the next release
