### ISSUE TITLE
Error in database

### ISSUE THREAD

**Issue by zybr78** [cmmcleod/coriolis#187]
You have an error somewhere in the database.
I collected viper
https://coriolis.io/outfit/viper/2p5t5F4l5dasdf12g2i1717000040582769.Iw1+kA==.CwBjGYxAmXrAjNcwg===?bn=Viper-war
You have shown the total energy consumption of 12.79, but in fact it is 13.28

**Comment by cmmcleod** [comment]
Can you please provide a screenshot(s) of your power management in-game showing all modules?

**Comment by zybr78** [comment]
I am sorry. It was my fault. confused

**Comment by cmmcleod** [comment]
No problem :)
