### ISSUE TITLE
Frame Shift Drive Interdictor Range

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#2]
Get actual ranges of FSD interdictors in Light seconds.

Add to `/data/components/internal/frame_shift_drive_interdictor.json` as `rangeLs`

**Comment by XeelS** [comment]
Where can you get that range? Experimenting in-game? Or there is an info on the forums?

**Comment by cmmcleod** [comment]
Don't have the info yet, and haven't been able to fund it on the forums. In-game testing is needed

**Comment by AlejandroHuerta** [comment]
This would be tedious to figure out considering they scale with speed.

**Comment by cmmcleod** [comment]
Ah, I thought there was a finite upper limit. Closing since this is impractical
