### ISSUE TITLE
Typo: Scanner range unit should be [ls], not [km]

### ISSUE THREAD

**Issue by fawick** [cmmcleod/coriolis#20]

**Comment by SpyTec** [comment]
No, scanners are in km. This is when they're in normal space

**Comment by fawick** [comment]
I should have been more specific. I'm talking about the Discovery Scanners for the Internal Compartment slots.For example, the Basic Discovery Scanner lists 500 km instead of 500 ls.

**Comment by i810697** [comment]
Easy to fix:  Change [this] (https://github.com/cmmcleod/coriolis/blob/master/app/views/_slot-internal.html#L15) fromKM to LS.  I would do it but it seems I cannot contribute to this github..?  
@cmmcleod I am trying to push a branch with the fix to trigger a pull request but it seems I am not allowed...

```
XXXXXXXXXXX:coriolis i810697$ git push --set-upstream origin issue-20
ERROR: Permission to cmmcleod/coriolis.git denied to i810697.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by cmmcleod** [comment]
Hey, couple of things.

Did you fork and then try to submit a PR? or did you clone the repo and are trying to push directly to a new branch in this repo? The latter won't work for security reasons. The best approach is to Fork and then send a pull request.

The range is actually supposed to be in KM (This is for the Kill Warrant Scanner, Cargo Scanner, and FSD Scanner). A separate attribute, that does not exist yet, is needed for FSD Interdictor range (for which I have no data yet). First I need FSD interdictor range data, See Issue #2 

So in this case KM is correct.

**Comment by i810697** [comment]
Currently:
![image](https://cloud.githubusercontent.com/assets/10167851/7817935/6a3a805e-03a6-11e5-8093-7196cc76e07b.png)

With fix:
![image](https://cloud.githubusercontent.com/assets/10167851/7817961/95fa6d94-03a6-11e5-8168-d1a44e95866c.png)

**Comment by cmmcleod** [comment]
My mistake! Good catch.

My suggestion is to change the range of the discovery scanners property to 'rangeLS', and add a new range Los property display. I can fix this.

Doing the above will also set things up for when we get FSD interdiction ranges (in LS).

Thanks for clarifying!

**Comment by i810697** [comment]
Great!   Sorry for being pushy then!

**Comment by fawick** [comment]
Thanks, @i810697!
