### ISSUE TITLE
Feature Request: Karma based user created build database.

### ISSUE THREAD

**Issue by PureDecimation** [cmmcleod/coriolis#26]
This would allow users to create builds, tag them with their use, and then have users vote on their effectiveness. 

I get dozens of requests a day from players on what build they should use for a ship. So having a place where we can upload baseline builds would be great, and the karma system could help weed out the bad builds (potentially could even remove builds below a certain level to help save storage server side).

**Comment by cmmcleod** [comment]
Cool idea, worth fleshing out and seeing if the community is interested and how they would like it to work.

**Comment by cmmcleod** [comment]
Closing for now. Will keep on the back burner
