### ISSUE TITLE
Desktop version with NW.js

### ISSUE THREAD

**Issue by Qirion** [cmmcleod/coriolis#27]
So, awesome work you have done here!
I could try to convert the tool to a desktop application using the NW.js.
I'm still learning how things work with this thing (I'm a java developer), but I think I could make it work.

**Comment by cmmcleod** [comment]
NW looks Interesting. I've just made changes (will release in 0.9.0) that makes Coriolis.io available offline on all modern browsers (including Mobiles and Tablets).

I'm certainly open to exploring the concept more. What would be the advantage of having a desktop app? (Other than having a window without browser crap, etc)

**Comment by Qirion** [comment]
What I have in mind is something like [EveHQ](http://evehq.co/). A tool with Galaxy map, outfitting, GalNet news feed, etc. I started working in a 2D map (java) that is organized with the jump range of the ship and I think, when finished it could be incorporated in the program, but it wouldn't be suitable or a full web based application.

**Comment by cmmcleod** [comment]
Since the app is now available offline (through appcache) I'm closing this for the time being
