### ISSUE TITLE
Cannot find module 'gulp-scp2'

### ISSUE THREAD

**Issue by Toxicat** [cmmcleod/coriolis#30]
~~You should add `npm install gulp-scp2 -g` in Developer's Guide/Dependencies.~~
I never used/installed gulp before and I got an `Error: Cannot find module 'gulp-scp2'` from `gulpfile.js::16`

~~EDIT 1 : `npm install gulp-scp2 -g` doesn't fix the error. Strange...~~

EDIT 2 : `npm install gulp-scp2 --save-dev` fix the problem

**Comment by Qirion** [comment]
I had the same problem, and with others modules. #31 should fix.

**Comment by cmmcleod** [comment]
Fixed!
