### ISSUE TITLE
Compare builds and see price difference

### ISSUE THREAD

**Issue by Hostail** [cmmcleod/coriolis#32]
Would make it easy too see how much it would cost to re-outfit a ship between a current build and a preferred build, and also see how much you would lose with selling and buying other modules.

**Comment by Hostail** [comment]
Feature Request*, forgot to put that in...

**Comment by cmmcleod** [comment]
This is a great idea.

Use Case 1:
1. Save a build
2. As changes are made show 'sold' components that have been replaced

Option to toggle this on/off in settings

Use Case 2:
Compare Ship A build 1 upgrade/downgrade to Ship A build 2.

**Comment by XeelS** [comment]
This. I was about to request it :P
Btw, thanks for your amazing work Leod, really impressive ^^

**Comment by XeelS** [comment]
Well, do not pay attention to the last sentence of my reply, it seems that I'm a little bit too tired. Good night /o
