### ISSUE TITLE
Wrong initial class of shield generator in Cobra Mk III

### ISSUE THREAD

**Issue by WojtekWZ** [cmmcleod/coriolis#36]
Initial generator on Cobra is 5E in a class 4 slot. It should be 4E.

**Comment by Toxicat** [comment]
Already fixed in cmmcleod/coriolis@4531afb198c2aa7e3a87329206c0cad025171bd5

**Comment by cmmcleod** [comment]
Hard refresh/clear browser cache should fix the issue.
