### ISSUE TITLE
Rename Diamondback to Diamondback Scout

### ISSUE THREAD

**Issue by i810697** [cmmcleod/coriolis#40]
![image](https://cloud.githubusercontent.com/assets/10167851/7963059/c9eed746-09de-11e5-82f7-fc6c9012f1a0.png)

**Comment by SpyTec** [comment]
This has already been changed, you might have to Ctrl+F5 to force refresh

**Comment by cmmcleod** [comment]
Already fixed in 0.10.0, you may need to refresh your cache, but thanks for the report!
