### ISSUE TITLE
Add the Diamondback Explorer

### ISSUE THREAD

**Issue by Toxicat** [cmmcleod/coriolis#42]
https://forums.frontier.co.uk/showthread.php?t=151259

Damn ! This beta bring us quite a lot of work !

**Comment by cmmcleod** [comment]
O_o

Marked as backlog for now!

**Comment by cmmcleod** [comment]
https://imgur.com/a/xOlUZ

**Comment by Toxicat** [comment]
I'm on it

**Comment by Toxicat** [comment]
Bulkhead data : http://i.imgur.com/JF3ndDW.png
