### ISSUE TITLE
Browser crash while dragging a photo

### ISSUE THREAD

**Issue by stummies** [cmmcleod/coriolis#46]
Browser: Chrome Version 43.0.2357.81 m
OS: Windows 8.1

When adding a photo to a ship in your fleet, if you follow these steps it will crash the browser completely:

1. Click photo box to open explorer to choose photo
2. Instead of clicking the photo and choosing open, drag the photo from the pop-up into the photo box.
3. Click cancel

Every time I do this the browser hangs and crashes.  When you drag the photo it shows up correctly like if you dragged it some other way.  I clicked cancel afterwards because I saw no need to choose open given that the photo already was showing correctly.

I tried with IE and Firefox, neither appear to allow me to drag from the pop-up window so they are as far as I can tell unaffected.  I also did try to drag the file from my desktop into Chrome which did work fine (as advertised).

If you need me to check anything else or provide more information I can.

**Comment by cmmcleod** [comment]
What do you mean by photo box?

I'm not sure what you are referring to since the app doesn't have any support for photos, or adding photos to a ship. 

Can you please provide some screenshots?

**Comment by cmmcleod** [comment]
Can you please elaborate on the issue you have? Screen shots, links, etc would be helpful
