### ISSUE TITLE
Can't add fuel tanks to internal slots

### ISSUE THREAD

**Issue by apemanzilla** [cmmcleod/coriolis#47]
As of 1.3, fuel tanks can be put in internal slots.

**Comment by cmmcleod** [comment]
Yeah, the following has not been added but will be in the nest release:
 - Internal Fuel Tanks
 - Collector Limpet Controllers
 - Prospector Limpet Controllers
 - Fuel Transfer Limpet Controllers

**Comment by cmmcleod** [comment]
Fixed. Will be in the next release

**Comment by apemanzilla** [comment]
Sweet, thanks!
