### ISSUE TITLE
Build DDL missing builds

### ISSUE THREAD

**Issue by Maverick-JM** [cmmcleod/coriolis#48]
https://forums.frontier.co.uk/showthread.php?t=147404&page=13&p=2339425&viewfull=1#post2339425

There's pictures here, but basically if you have too many builds they don't show up in the builds drop down it seems like. I added 45 to my local and it worked ok, but they were of less types than that link, I'll add the exact same builds now and try to reproduce the issue.

**Comment by cmmcleod** [comment]
All of the menu's scroll once they exceed the max height.
