### ISSUE TITLE
Saved builds visual bug

### ISSUE THREAD

**Issue by rlex** [cmmcleod/coriolis#51]
When N of saved builds is uneven, it ends up like this:

http://i.imgur.com/IA2dbYw.png

(for some reason, can't upload screenshot to GH)

**Comment by cmmcleod** [comment]
Yeah, this is due to the column layout. This will be tweaked/fixed in the upcoming release.

Thanks for the report!

**Comment by cmmcleod** [comment]
Sidenote: Love the Anaconda - Dreams build name :)

**Comment by cmmcleod** [comment]
Fixed in master. Will be in the next release.
