### ISSUE TITLE
Power-priority widget on Outfitting screen is awesome...but needs some tweaks on phones.

### ISSUE THREAD

**Issue by Maverick-JM** [cmmcleod/coriolis#52]
Finally got around to merging back to my fork - the priority thing is *awesome*. However, it needs a few little tweaks on phones. I'll take a look at this today (got this lovely winters day off work :)).

**Comment by cmmcleod** [comment]
I literally just pushed some changes :) Let me know what you think.

The solution i have right now is to have a min of 600px and scroll on overflow. Feel free to tweak!

Glad you like it :)

**Comment by cmmcleod** [comment]
And thanks for the help ;)

**Comment by Maverick-JM** [comment]
No probs - I am partially self motivated, in that I generally would much rather use my phone for toying with outfits than my PC :).

I made some tweaks (pull request incoming...).

**Comment by Toxicat** [comment]
> the priority thing is awesome
Glad you like it to ! :)

**Comment by Maverick-JM** [comment]
It's pretty damn useful :). Even in-game the module screen doesn't do a good job of what will and won't work when everything is deployed. This will be very handy - particularly for planning out FDL, Viper and Vulture builds which are fairly power hungry.

**Comment by cmmcleod** [comment]
Merged your fixes
