### ISSUE TITLE
upgrade price feature

### ISSUE THREAD

**Issue by rlex** [cmmcleod/coriolis#60]
Feature request.

Something like this:

1) Make a build. I keep my current ships saved in coriolis.
2) Press, for example, "snapshot" button. Really can't come with better name.
3) Change some modules. Coriolis should now show price difference between current ship and proposed upgrade.

**Comment by rlex** [comment]
eh, probably dupe of #32, sorry.

**Comment by cmmcleod** [comment]
Closing in favor of #32
