### ISSUE TITLE
Other Discounts

### ISSUE THREAD

**Issue by Tyroo** [cmmcleod/coriolis#61]
Add Li Yong-Rui 15% Discount to Ships and modules

Add Alioth 20% Asp and Orca Discounts

others that I don't know

**Comment by cmmcleod** [comment]
I'll add 15% and 20%  discounts for ships and modules. I will add a seperate discount for ship vs modules/components. 

We will not be adding support for discounts for specific ships.

**Comment by Tyroo** [comment]
Thanks! The Sirius 15% was the main one since I know a lot of players are starting to buy there.

Tyler Roche
