### ISSUE TITLE
Discounts again

### ISSUE THREAD

**Issue by rlex** [cmmcleod/coriolis#63]
Zachary Hudson controlled stations offers 25% discount on ships and 20% on outfitting (it seems)
LHS 3447 - Dalton Gateway: 20% Discount.
Needs verification but i surely got python and some nice modules for a neat discount at Bhrtizamento, Feyman Terminal.

**Comment by rlex** [comment]
[Here is a nice thread about active discounts](https://www.reddit.com/r/EliteDangerous/comments/3alrgh/active_discounts_for_elite_for_all_players_none/)

**Comment by cmmcleod** [comment]
Added discounts from 5 - 25%, this will go live later today
