### ISSUE TITLE
Power Play Components

### ISSUE THREAD

**Issue by cmmcleod** [cmmcleod/coriolis#67]
Data needed for the following Power Play special components:
 - Pack-hound Rack (missile launcher [seeker])

**Partial Data:**
 - Need Cost/Price:
    - Cytoscrambler (burst laser)
    - Pacifier Frag-Cannon
    - Pulse Disruptor (Medium Laser) 
    - Retributor (Small Beam  laser)
    - Mining Lance (mining laser)

**Complete:**
:heavy_check_mark: Advanced Accelerator (plasma accelerator)
:heavy_check_mark: Imperial Hammer (railgun)
:heavy_check_mark: Enforcer Cannon
:heavy_check_mark: Prismatic Shield Generators

**Comment by cmmcleod** [comment]
Thanks :)

**Comment by cmmcleod** [comment]
Pulling data from this thread

https://forums.frontier.co.uk/showthread.php?t=163555

**Comment by warox974** [comment]
Ho ok ! Great I gonna bookmark this one more page of Frontier Forums :p

**Comment by cmmcleod** [comment]
Data commited from fd68565d8e88ae5ce2e832ba56462417eaa1ec51 onwards

**Comment by cmmcleod** [comment]
Thread to collect and verify prices:

https://forums.frontier.co.uk/showthread.php?t=165165
