### ISSUE TITLE
Export with stats feature (similar to E:D Shipyard)

### ISSUE THREAD

**Issue by jschnarr** [cmmcleod/coriolis#68]
I'm the developer of ETN (http://etn.io) and would like a way to import key build info from Coriolis (ship name, full mass, FSD stats, fuel and cargo). It's been requested. Something similar to E:D Shipyard's export with stats would be great. I see there is a packed json export but I'd rather not write (and maintain) a parser for that. The ideal format would be json with all the components separated.

**Comment by cmmcleod** [comment]
Happy to oblige!

Would you prefer JSON over the ED Shipyard format? If so, can you provide an example of what you would like the JSON to look like (full schema not needed, just a dummy example)

**Comment by jschnarr** [comment]
I certainly wouldn't object to the ED Shipyard format (with cargo/fuel/mass stats). I already have the parser for it and it is becoming more commonplace... EDMC dumps it as well (including loadouts straight from the game). But if you have to write the exporter anyway, JSON would be cleaner in the long run and it trivializes parsing. I was thinking something like this:

{
"$schemaRef": "http://blah",
"builds": {
    "My Sidewinder": {
        "ship": "Sidewinder",
        "components": {
            "standard": {
                "bulkheads": "Lightweight Alloy" ,
                "powerplant": { "class": 2, "quality": "E"},
                "thrusters": { "class": 2, "quality": "E"},
                "frameshiftdrive": { "class": 2, "quality": "C"},
                ...
            },
            "internal": [
                { "shield": { "class": 2, "quality": "E"}},
                { "cargo": { "capacity": "4"} },
                { "cargo": { "capacity": "2"}},
            ],
            "hardpoint": [
                 ...
            ],
            "utility": [
                 ...
            ],
        },
        "stats": {
            "mass": {
                "full": 44.9,
                "empty": 50.9,
            },
            "range": {
                "laden": 6.96,
                "unladen": 7.56,
            },
            "cargo": 4, 
            "fuel": 2,
            "price": 32000,
        },
    },
}

**Comment by gbiobob** [comment]
Hi!
same needs on my side for http://en.ed-board.net, registered users can save their coriolis builds, could be nice to have easily more basic infos about the builds,
a JSON like jschnarr proposal could be perfect :)
Already see how to extract all datas from url but could be perfect if we can have those data directly.

I see two ways to get the datas :
1) let the user having a optional semi-full/full export and then the user can copy-paste it in other apps
2) or maybe by adding an api to get the JSON of the config ID we have in the url, something like that : 
http : //coriolis.io/json/04E4E4E3E3E3E4C1717----02024900-2h.Iw1-kA==.Aw1-kA==

Find the second option better,the user keep a simple export & the external app will make the rest, but will make more request on your host :/ (you will have to check if an other app don't abuse of the api by making too request).

**Comment by cmmcleod** [comment]
@gbiobob @jschnarr I've committed a draft schema and have implemented its serializer/exporter.

Schema
https://github.com/cmmcleod/coriolis/blob/master/app/schemas/ship-loadout/1-draft.json

Example JSON
https://gist.github.com/cmmcleod/5d232bcbd8b10f5c6f0f

Link to Build
http://coriolis.io/outfit/anaconda/48A6A6A5A8A8A5C2c0o0o0o1m1m0q0q0404-0l0b0100034k5n052d04--0303326b.AwRj4yo5dig%3D.MwBhEYy6duwEziA%3D?bn=Example

Let me know what you think.

**Comment by jschnarr** [comment]
Looks great. I was surprised to see the null components at first. Then I
realized they are empty slots. Makes sense. Are you planning to add an
additional export option for this? Should be simple to parse/process this.

**Comment by cmmcleod** [comment]
Yes, I'm planning on adding (it's actually already done, just hidden) export for a single build on the outfit page, and 'Detailed Export' option which will be an array of the build objects (I'll create a separate schema for this).

**Comment by gbiobob** [comment]
Seems perfect ;)

**Comment by cmmcleod** [comment]
Releasing version 1 schema later tonight.

In the Settings menu there will be a '3rd Party Export' option which will produce a JSON array of all builds using the schema (will be released at version `1`, not version `1-draft`).

There will also be an 'Export' option in the outfitting page which will produce a single JSON Object of the build/loadout.

**Comment by gbiobob** [comment]
Small question : Is the 3rd Party Export will be importable in the actual Coriolis import ?
On my side, I see two use case for the export : have a small list of ships with some stats in my app but also offer a way to save the user's builds if they loose theirs data on Coriolis (localstorage cleared).

**Comment by cmmcleod** [comment]
I'm working on that at the moment.

Corilois will import both the existing export, and the 3rd Party Export

**Comment by gbiobob** [comment]
Perfect!

**Comment by cmmcleod** [comment]
Took a bit longer to get the import working as nicely as I wanted. Also added a good amount of automated testing to catch some edge cases:

Hardpoints - Mount type is required, updated the JSON schema to reflect this.

There are weapon typess that have the same class and rating but different mounts (F/G/T). 

Will release in a few mins!

**Comment by gbiobob** [comment]
Thanks a lot!

**Comment by jschnarr** [comment]
Nice work! I added import support to ETN. The JSON made it very easy :)

**Comment by cmmcleod** [comment]
Excellent :) Don't hesitate to submit any issues regarding bugs or improvements.
