### ISSUE TITLE
Suggestion: add "Public" option to share loadouts

### ISSUE THREAD

**Issue by ElChalo** [cmmcleod/coriolis#70]
I would love to see others' loadouts, as long as they share it, without having to google around for posts on reddit/fdev. I thought it might be nice if we could have a "public" checkbox on saved ships which would then make them available for others to see (perhaps in a list, filterable by ship type, cost range, etc?).
I admit I haven't looked at the code, but It seems to be saving locally (i.e.: no database) so this might not be easily implementable right now, but I thought maybe the idea was worth mentioning.
Thank you for such a great tool!

**Comment by cmmcleod** [comment]
This has been suggest in a number of different ways and is being tracked in #12 

Right now this is a client-side only app so there is no database (to keep performance high, and hosting costs really low). However, it is something that will come in time.

Closing in favor of #12
