### ISSUE TITLE
Orca's first 2 slots only take cargo racks or hull reinforcement

### ISSUE THREAD

**Issue by freiheit** [cmmcleod/coriolis#73]
I was trying to play with an [Orca](http://coriolis.io/outfit/orca/) config, and I've found that the class 6 internal compartment and the first class 5 internal compartment only offer empty, cargo rack and hull reinforcement options. No way to, for instance, try it out with a 6A shield generator.

**Comment by freiheit** [comment]
Found [other documentation online](http://elite-dangerous.wikia.com/wiki/Orca) corroborating that this is correct for this ship.

**Comment by cmmcleod** [comment]
Yes, the Orca is a strange exception
