### ISSUE TITLE
Support other locales (i18n, l10n)

### ISSUE THREAD

**Issue by gingters** [cmmcleod/coriolis#76]
It would be great if Coriolis.io would support other locales to, i.e. german.

This would mean support of translating the UI (Views) and the names of the components in the data, and pick the locale based on the browsers preferences settings.

I would also offer help here and actually doing that, but I want to discuss the preferred approach here before jumping in and suprising everyone with a pull request that goes the wrong way.

That said, I currently don't have real-world angular experience, so I may need a bit of guidance to jump in.

**Comment by cmmcleod** [comment]
Thread for language support:

https://forums.frontier.co.uk/showthread.php?t=176714

Spreadsheet for translations:
https://docs.google.com/spreadsheets/d/1fS2priAOwb13oLyfLgne2Kcff9NJ0Pxa8dRzr8LukcY/edit?usp=sharing

I've looked into the technical aspect and Angular Translate seems to be a great option:
https://angular-translate.github.io/

**Comment by cmmcleod** [comment]
Will be released in 1.5.0 

Translation issues / errors will be tracked as separate issues
