### ISSUE TITLE
Insurance amount sometimes incorrect

### ISSUE THREAD

**Issue by nemesyssoft** [cmmcleod/coriolis#77]
I've got a Python that is all A-spec'd. On Coriolis, the amount of insurance is 6,080,815 CR but, in game, it reports my insurance to 5,585,819 CR. This is a beta insurance. I selected it in the coriolis settings.

**Comment by nemesyssoft** [comment]
![screenshot_0032](https://cloud.githubusercontent.com/assets/2309889/9319910/c5f54ad4-4521-11e5-9eb3-7716e96fce12.jpg)

![python - laurent python](https://cloud.githubusercontent.com/assets/2309889/9319932/eb08c15c-4521-11e5-9845-8ae1402f404c.jpg)

**Comment by cmmcleod** [comment]
Did you purchase any components at stations with a discount?

**Comment by nemesyssoft** [comment]
Hey Colin.

Yes, I did buy a few components at stations with discount. I guess that’s were the disparity comes from.

I guess that will be impossible to adjust?

-Laurent.
-- 
Laurent Daudelin							laurent@nemesys-soft.com <mailto:laurent@nemesys-soft.com>
AIM/iChat/Skype:LaurentDaudelin 				http://www.nemesys-soft.com/ <http://www.nemesys-soft.com/>
Logiciels Nemesys Software

**Comment by cmmcleod** [comment]
Essentially yes. I did play around with having an interface with discounts on individual components, but it was cumbersome, and not particularly user-friendly.

I will revisit this.
