### ISSUE TITLE
power draw values

### ISSUE THREAD

**Issue by YinYin-Falcon** [cmmcleod/coriolis#80]
This load out gets me a perfect 100% deployed power draw, which in game still disables all modules (red 100%):
http://coriolis.io/outfit/viper/33A3D3A2E3A3E2C1b1b2929040l402t2f2i.AwRhrSvcg===.IwBhrSvcg===?bn=Impact%20Viper
Is the database or limit check off?

**Comment by cmmcleod** [comment]
This is probably due to a rounding error as Coriolis only uses numbers that are listed to 2 decimal places, where the actual in-game values may vary slightly as they are rounded up. I'll do some testing and investigating to see if this can be narrowed down

**Comment by cmmcleod** [comment]
It seems the in game logic does not allow 100% exactly, i.e. 100% means you've used too much power. Changing the warning to show at 100% and over. This will be in the next release
