### ISSUE TITLE
Ability to Mark Component as Powered Down

### ISSUE THREAD

**Issue by evoelise** [cmmcleod/coriolis#86]
It would be great if there was an option to power off a component (as well as the current selection of priority) on the designer. 

Many players, especially for combat, over-stack their ships energy-wise and only turn on items that are needed, many items being turned off until needed such as cargo hatch, SCBs, Fuel Scoops etc.

Note that some items cannot be turned off - such as the power plant.

**Comment by cmmcleod** [comment]
You can already power off a component simply by clicking on it's name.
