### ISSUE TITLE
compare power

### ISSUE THREAD

**Issue by YinYin-Falcon** [cmmcleod/coriolis#87]
It would be great if the power bars on the compare view would also reflect disabled modules instead of only showing the total power draw of all modules.

**Comment by cmmcleod** [comment]
They already do:

http://goo.gl/lhAvVl

Is this not what you mean?

**Comment by cmmcleod** [comment]
Closing since this is already implemented.

**Comment by YinYin-Falcon** [comment]
No, I mean something like this:
http://coriolis.io/outfit/sidewinder/22A2A2A1A1A1A1C--0e043r53-.Iw19A===.IwBhuU0gmSg=?bn=test
The "used" power (all modules) often exceeds my available power and I use certain modules only in deployed/not deployed mode - the build view reflects that with red bars, the power comparison view does not seem to reflect that.

**Comment by cmmcleod** [comment]
No, the comparison view uses a different color to highlight deployed, retracted and available power. They will not show power bars broken down by priority. This isn't likely to change anytime soon.
