### ISSUE TITLE
Ship Images

### ISSUE THREAD

**Issue by smartroad** [cmmcleod/coriolis#88]
Not an issue, just a thought. Would it be possible to have ship images on the home page and maybe the build page?

If the site gets accounts could be that people add thier own images for their builds?

As Cave Johnson said, just throwing science at the wall here to see what sticks ;)

**Comment by cmmcleod** [comment]
Ship images on the homepage = Yes, and it is something I will get around to soon. I am planning on overhauling the whole page.

Ship images on the build page - Maybe, it doesn't add value and takes up valuable screen real estate, so probably not.

Upload own images - I don't thinks so; it adds little value, but increases the difficult of running the site (hosting for images, additional complexity for uploading, etc).
