### ISSUE TITLE
SCB Cell count is off by one

### ISSUE THREAD

**Issue by jasonleepeacock** [cmmcleod/coriolis#90]
I've noticed that all the Shield Cell Bank's Cell count is off by +1.  The Coriolis shows B rated SCBs having 5 cells, but in-game, there are only 4 cells available.  The other rated SCBs correspondingly show 4 cells on Coriolis, while in-game there are only 3 cells available in an SCB.

Unless there's some hidden feature in the game I have overlooked that unlocks an extra cell in an SCB.

(I'm referencing 1.3 version of the game)

**Comment by cmmcleod** [comment]
This was changed in this commit 95adca5cdea60d7fe16658b8d522f9ad9a07b549 by @sf302 

I gave the committer the benefit of doubt here. It looks like this change was incorrect. I will double check and fix (if you have a screenshot that would helpme confirm too). As far as I know there are no changes in 1.4 that will reflect this either.

**Comment by sf302** [comment]
If you look in the Modules tab you'll see that a 2B SCB shows (1/4) in the ammo count when you're in flight. Using one cell puts it at (0/4) until it's done reloading at which point it becomes (1/3). This continues until you use another cell at (1/0) state and it can't reload at that point and stops at (0/0).

A 4A for instance shows (1/3) after a fresh rearm.

When in doubt, the ultimate authoritative count for ammunition is the Munitions tab in Station Services. I meant to correct the medium torpedoes ammo count by the way (2/0) at launch, not (2/1) but just hadn't gotten around to it.

**Comment by cmmcleod** [comment]
And you are certain it doesn't go from 1/1 -> 0/0 after using the cell?

**Comment by sf302** [comment]
Yep.

Here's a clip for verification (4A SCB): http://kncg.pw/PSynPXX.webm

Munitions tab displays 4 charges as well after docking: http://kncg.pw/gQLK7ZS.jpg

**Comment by cmmcleod** [comment]
[SCB Tests](http://i.imgur.com/p2t0PkV.png)
Source: [All Shield Cell Banks Tested in Actual Shield Values](https://forums.frontier.co.uk/showthread.php?t=137188)

[Shield Cell Bank Wiki](http://elite-dangerous.wikia.com/wiki/Shield_Cell_Bank) confirms this too (with the exception of class 7 and they are missing class 8 - which seems to be an error on their part)

**Comment by cmmcleod** [comment]
Not a bug @sf302 is correct! (Thanks for responding and confirming so quickly.

**Comment by sf302** [comment]
The confusion for both initial issue that my commit fixed and this current issue likely stemmed from expecting a 1/3 number to mean '1 of 3' when instead (almost) everything with that notation in the game actually means 'loaded/reserve'.

Do you want me to file a pull request to fix medium torpedo ammo--shown as (2/0) in Modules and  '2' in Munitions tab--or is it quick enough a fix that it doesn't warrant it?

**Comment by cmmcleod** [comment]
@sf302 I can fix this.

To confirm:
Total/Max ammo is 2
Clip size is 2
Therefore Additional/Reserve Ammo is 0

If this is not correct / what you mean, then yes please submit a PR :)

**Comment by sf302** [comment]
Yep that's correct. When I get around to having something substantial enough for another PR I'll verify class 1 torpedoes at that time and include it at that time.
