### ISSUE TITLE
Boost speeds are not correct.

### ISSUE THREAD

**Issue by Bimnomercy** [cmmcleod/coriolis#91]
My Imperial Clipper with 6B class thruster is able to reach 420 m/s with boost, but in Coriolis.io, it is annouced for 388 m/s. On the other side, thruster class doesn't seem to change boost speed, but in game, it does.

**Comment by cmmcleod** [comment]
Boost speeds are static right now (there is no function to model this yet). Right now they are hard-coded to anecdotally highest reported values. 

Working on improvements to this.

**Comment by sf302** [comment]
For what it's worth, my FDL at 417T (below the 50% optimal mass for 5A thrusters) hits 406 boost, which seems to indicate that taleden's 1.16x ratio applies to boost speed as well.

**Comment by cmmcleod** [comment]
@sf302 Which 1.16x ratio are you referring to? I've clearly missed it!

**Comment by sf302** [comment]
https://forums.frontier.co.uk/showthread.php?t=182057

**Comment by cmmcleod** [comment]
Fer-de-Lance base boost speed is 357. 357 * 1.16 = 414.1 which isn't that close to 406.

**Comment by sf302** [comment]
I was going off of the old 350 number actually. Does the 357 already account for out of the box mass with E-rated thrusters?

**Comment by cmmcleod** [comment]
Fixed in 231fcbb3bcecfbb9189159164a24cbc3e9ddbaae

Will be released in 1.7.0

**Comment by Bimnomercy** [comment]
The correction is visible in Configuration screen but not in comparaison charts.

**Comment by cmmcleod** [comment]
Yup. Oversight on my part! Will fix.
