### ISSUE TITLE
Add a 50% power plant column to the power settings

### ISSUE THREAD

**Issue by spullara** [cmmcleod/coriolis#98]
In 1.4 you are going to have 50% power if you power plant is brought to 0%. it would be great to see right on the power settings panel what that will mean for you. Should make it easier to ensure that things like your thrusters are still working when this happens.

**Comment by cmmcleod** [comment]
I was thinking something along these lines

<img width="776" alt="screen shot 2015-10-05 at 6 13 13 pm" src="https://cloud.githubusercontent.com/assets/823967/10297878/5a3d2180-6b8d-11e5-8a37-c717787b1c34.png">
<img width="794" alt="screen shot 2015-10-05 at 6 14 06 pm" src="https://cloud.githubusercontent.com/assets/823967/10297877/5a3c98f0-6b8d-11e5-93e8-a269b309bd13.png">

Showing a warning when priority 1 exceeded 50%

**Comment by spullara** [comment]
Might be ok? Reduces the clutter in the table at the expense of being a little bit hidden. Would the line be on top of the bars if they go above 50% or below?

**Comment by cmmcleod** [comment]
the line would always be on top

**Comment by cmmcleod** [comment]
Implemented in a4b8b942a142e21dacac2d7cb68fba07e02a0ec9

Updated Screenshots:

<img width="802" alt="screen shot 2015-10-07 at 2 16 10 am" src="https://cloud.githubusercontent.com/assets/823967/10333571/b0badc52-6c99-11e5-913b-d543614feb79.png">
<img width="805" alt="screen shot 2015-10-07 at 2 16 24 am" src="https://cloud.githubusercontent.com/assets/823967/10333572/b0bbb258-6c99-11e5-8a05-36c396d51567.png">

**Comment by cmmcleod** [comment]
in the next release (1.9.x) i am planning on adding tool tips which will help with more obsure features such as this

**Comment by cmmcleod** [comment]
closing
